### ISSUE TITLE
Chrome extension

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#100]
I've had a bit of time this weekend and decided to implement a chrome extension for this password manager. https://github.com/BenjaminHae/PwChromeExtension
It is very unfinished, but the basic functionality is ready.
Just install it and login to your password manager. Afterwards right click on any webpage's input field and check out the Password-Manager menu.

It only works if you use the "url" field in the password manager.

Current problem is: the data in the plugin is only deleted when closing chrome. This will be fixed when I've got time again.

If you like the extension, I'd be happy if you mention it in your Readme.

**Comment by zeruniverse** [comment]
Sure. Just help yourself to add it in README whenever you're ready! But I suggest you to add this in README of my repository after your first release (I.e. Solve the problem you mentioned).

**Comment by zeruniverse** [comment]
Sure. Just help yourself to add it in README whenever you're ready! But I
suggest you to add this in README of my repository after your first release
(I.e. Solve the problem you mentioned).

**Comment by zeruniverse** [comment]
Done.
