### ISSUE TITLE
Questions about implementation of sessions

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#102]
Is there a reason the `session_token` is generated on the client?(`index.php`)
```
var session_token=getpwd('1234567890abcdefghjklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ',50);
sessionStorage.session_token=session_token;
```
It could be set by the server(and this would probably make opening two password-manager instances at the same time easier). The [example for csrf prevention](https://www.owasp.org/index.php/PHP_CSRF_Guard) at owasp does it this way.

Why don't we call `session_destroy ( void )` when logging out(`logout.php`)? Deleting the session of a authenticated session is best practice as it prevents reusing of the session by others.

(The first question is mainly because of my addon, the second one is out of curiosity and the desire to make this password manager as secure as possible)

**Comment by zeruniverse** [comment]
Well I forget why I did it… will try to recall.

**Comment by BenjaminHae** [comment]
Another thing: the session id should be regenerated after login([Renew the Session ID After Any Privilege Level Change](https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Renew_the_Session_ID_After_Any_Privilege_Level_Change), this also fits to the second question)

**Comment by zeruniverse** [comment]
Oh! Then I know why I did this. I might try to make session ID different every time the user logins?

**Comment by zeruniverse** [comment]
But I think PHP did this itself...

**Comment by zeruniverse** [comment]
I won't against it if you want to move the token generation to server side

**Comment by BenjaminHae** [comment]
It turned out none of these changes were necessary for the addon to work. I think they are just generally a good idea.
