### ISSUE TITLE
Not possible to signup

### ISSUE THREAD

**Issue by forvalak** [zeruniverse/Password-Manager#104]
Hello!

After installation I tried to register a user, but it failed with the error "There're some errors, please retry".

Nothing happens, also no entry in the DB.

PHP-Log: 
`PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2002] No such file or directory in /var/www/PassManager/src/function/sqllink.php:19`
`Stack trace:`
`#0 /var/www/PassManager/src/function/sqllink.php(19): PDO->__construct('mysql:host=loca...', 'passwordmanager', 'dMqXXYslI7tyXcF...', Array)`
`#1 /var/www/PassManager/src/reg.php(8): sqllink()`
`#2 {main}`
`  thrown in /var/www/PassManager/src/function/sqllink.php on line 19`

**Comment by zeruniverse** [comment]
Looks to me that you don't have PDO support. As said in README, PDO support
must be installed to run this password manager. To verify it, you can print
out phpinfo() and search for keyword PDO.

You can install PDO support for PHP to fix it. (Package name should be
something like php-pdo)

**Comment by forvalak** [comment]
It seems to be installed:
`/bin/php -i|grep PDO`
`PDO`
`PDO support => enabled`
`PDO drivers => dblib, mysql, odbc, pgsql, sqlite`
`PDO Driver for FreeTDS/Sybase DB-lib => enabled`
`PDO Driver for MySQL => enabled`
`PDO_ODBC`
`PDO Driver for ODBC (unixODBC) => enabled`
`PDO Driver for PostgreSQL => enabled`
`PDO Driver for SQLite 3.x => enabled`

PHP version is PHP 7.0.9
Apache version is Apache/2.4.23 (Unix)

Thank you in advance.

**Comment by zeruniverse** [comment]
Umm. To be honest I never saw this bug before. Line 19 is simply constructing a PDO connection. I don't know why it reported an error there…

I did find some resources for you: http://stackoverflow.com/questions/20723803/pdoexception-sqlstatehy000-2002-no-such-file-or-directory

Please let me know if the above link solves your problem

**Comment by forvalak** [comment]
Ok, it solved my problem :)
I changed the DB_HOST from localhost to 127.0.0.1.

Thank you!
