### ISSUE TITLE
Password box

### ISSUE THREAD

**Issue by stevetoza** [zeruniverse/Password-Manager#105]
Hello, 

Just started using Password-Manager and noticed that if you click to show a password and the password has a "<" sign in the password the password is only shown up to the "<" sign. The rest of the password is cut off. 

Thanks

**Comment by zeruniverse** [comment]
I think it's because the < not being escaped. Could you check the HTML
source and see whether password there is correct?

I never thought this problem before since I myself never use <> or & in my
password.

**Comment by BenjaminHae** [comment]
I think if we use `$().text("heregoesthestring<>");` for setting output everything should be handled by jQuery the way we want it.

**Comment by stevetoza** [comment]
That fixed it :) Many Thanks
