### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#107]
Maybe we could rename the project. "Password Manager" is a bit generic ;).
Especially when I'm publishing the addon to the Chrome Web Store. Users looking for "Password-Manager" could lead to confusion. (When looking for the addon or when looking for the host-software). 

Maybe someone has a catchy idea? This could be a way to increase visibility of this project. (If we really want this is another question).

**Comment by zeruniverse** [comment]
I consider GitHub project name as a label of the project. It shouldn't be long. Otherwise, the URL will be too long.

Of course, when you advertise the project, you can describe it as specific as you like. It's not necessary for you to use exact [GitHub project name].
