### ISSUE TITLE
Layout with more fields

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#11]
Implementations of tags and urls,... is sufficiently far to talk about layout.
At the moment it looks like this
![without](https://cloud.githubusercontent.com/assets/7386033/13197405/5f30262a-d7ed-11e5-9196-fe90643c24e3.png)
Empty columns are being hidden. So if you don't need one type of field you just ignore it.
All Columns but account, username and password are hidden when in mobile mode.

I want to add a button for editing an account and a button for opening the url associated with an account.

What do you think is the most intuitive position for them?
My idea is to open the url when clicking on the account name. Add a little settings button after the account name. But maybe those two "clickables" are to near together for mobile.

I'd further move the regeneration of passwords and the removal of accounts into the editing dialog.

**Comment by zeruniverse** [comment]
I think make account clickable is good.

BTW, if you split account name into account and username, I don't think you should hide username in mobile.

Since I didn't touch too much about this feature, I would simply accept your pull request for this as long as it works

**Comment by zeruniverse** [comment]
Also, the idea of hiding all empty column is good

**Comment by zeruniverse** [comment]
I tested on my mobile phone.  Hiding username will make it looks better... And I add an icon beside the account for editing. since by clicking the account name, one might just want to copy it... I already did them in new commits
