### ISSUE TITLE
Not working on IEMobile

### ISSUE THREAD

**Issue by Pofilo** [zeruniverse/Password-Manager#113]
Hi !

I'm using my own instance of Password-Manager on [my fork](https://git.pofilo.fr/pofilo/password-manager) but I noticed a bug appearing in a commit here !

Here is the problem: everything is working fine on computers, (correct characteristics) smartphones .. but not with a small characteristics smartphone (a LUMIA 520 with Qualcomm MSM8227 - 1 GHz and 512 Mo RAM). As it is on my fork, I tried on the "official" version of the manager and it didn't work too.

After few researches, I found that this commit about encoding (https://github.com/zeruniverse/Password-Manager/commit/8a3e985641475014c843fba9d85a87d6b7ba8dd9) was the source of the problem.
After few other resarches, I determined that the problem was this commit https://github.com/zeruniverse/Password-Manager/pull/108/commits/a0ef557f127601286ff39b3b4ea82e7aa02a33d3.

If I revert only this commit, it works well on the device, but I don't really understand the reason of that !
I'm not so bad but not so good in web languages and I don't find a logic in there. If you have an idea that might explain this strange thing :)

Otherwise, happy new year ! ;)

**Comment by zeruniverse** [comment]
I'm currently on vacation. I might not look into this issue in coming days.

**Comment by BenjaminHae** [comment]
@Pofilo could you elaborate on the browser versions? Maybe there is a known problem in jQuery.
All of the functions used in the commit seem pretty standard.

**Comment by zeruniverse** [comment]
Sorry for late reply. I was on vacation.

Is this issue solved? @Pofilo

**Comment by Pofilo** [comment]
I didn't succeed to find the exact browser version ...
But it is Internet Explorer Mobile.

I found some informations about issues with this browser and jquery ([https://cdivilly.wordpress.com/2008/01/10/jquery-on-internet-explorer-mobile/](https://cdivilly.wordpress.com/2008/01/10/jquery-on-internet-explorer-mobile/).

I'm not sure it is really relevant to solve this problem as this browser is not really used by a lot of people.

**Comment by zeruniverse** [comment]
Never heard of this browser before, to be honest... and I don't want to support it... what do you think @BenjaminHae ?

**Comment by Pofilo** [comment]
I do agree, there is no problem of no supporting this browser.
Btw, I will rename this issue as the problem is more identified.

**Comment by BenjaminHae** [comment]
@Pofilo Have you tried to update jQuery? It's on version 2.0.0 in this repository. Maybe someone took care of this issue?

**Comment by BenjaminHae** [comment]
@Pofilo you've done some useful things on your repository(for example the copy to clipboard function or the setting to (dis-)allow signup). If you have the time could you create pull requests so we can merge these upstream?

**Comment by Pofilo** [comment]
I wanted to ask you to do it before because there is some little "bugs".

The copy to clipboard function doesn't work on every browser (like on iOS). 
For the (dis)allow signup, i'm not sure it's working 100% (can someone create by his own the request and send it) because i just disable the signup button.
But sure, I can create pull requests for that ! (I will have time tomorrow or this week-end !)

**Comment by zeruniverse** [comment]
@Pofilo To disallow signup, you need to delete the backend php file as well. That way, there's no way to sign up since the backend file is deleted

**Comment by BenjaminHae** [comment]
@Pofilo Could you please open [this html file](https://gist.github.com/BenjaminHae/00a9257732c19c5d0c24dab32d56cb18) on one of the devices where the manager is broken. If the output is different than on a device where the manager is working we could find out what change exactly is the problem.

**Comment by Pofilo** [comment]
I can't do that before 2 or 3 weeks as I don't have actually the mobile with me.

I close this issue during this time and I fork your test project just in case.

**Comment by Pofilo** [comment]
So I juste test the _html file_ on the device and it was working (Check 1 and 2 appears).

**Comment by BenjaminHae** [comment]
Well that's weird. The selected commit doesn't use any other relevant jQuery functions.

Maybe it's about bootstrap? But I can't see why.

**Comment by Pofilo** [comment]
Okay, no problem ! It's not a device used by a lot of person so it's not necessary to focus on that problem.

Thanks for your time :)
