### ISSUE TITLE
Where to set  session cookie params

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#114]
I want to use `session_set_cookie_params` to set parameters like `secure` or `httponly` for the session cookie. My favorite place to put this would be `function/sqllink.php`, because it's included in most files where `session_` functions are called. Sadly it's not included in `logout.php` where `session_destroy` is called.
What would you suggest?

I will remove most manually called `setcookie` to reduce points where we could set insecure cookies by accident, as `session_start` already does that for you.

**Comment by zeruniverse** [comment]
Can we just simply destroy everything in the `logout.php`? Like:
``` PHP
<?php
session_start();
session_destroy();
?>
```

If not, I would suggest include `sqllink.php` into `logout.php`

**Comment by zeruniverse** [comment]
Sorry for late reply. I was on vacation.
