### ISSUE TITLE
e-mail addresses are only validated on the user side.

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#117]
When signing up user e-mail addresses are only validated locally on the user's client.
This allows the user to manually craft a http request to signup a new user without a valid e-mail address.

Solution: the e-mail address parameter should be checked in `reg.php`

**Comment by zeruniverse** [comment]
I used the e-mail address to do 2-step authentication in my own version. In
the GitHub version, the e-mail address is not used and therefore, it's ok
if not valid.
