### ISSUE TITLE
import_raw, json status

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#12]
I think to check if the json data is valid it shouldn't be
`if(json.status!="RAW_OK")`
but
`if(json.status!="OK")`
at least that's what chrome is showing.

**Comment by zeruniverse** [comment]
No. If you read the README, you can find out that the backup you generated is encrypted without the key. This, user should go to recovery to recover the password before it can be imported. This backup can be safely saved in other places. The recovery page can generate another json file without protection, that status is RAW_OK. This should only be used to transfer your password into other places. Saving this file is dangerous
