### ISSUE TITLE
Login not working for me with latest release

### ISSUE THREAD

**Issue by nickbe** [zeruniverse/Password-Manager#127]
made a new instance and tried to setup/login.
Database is setup correctly. The user record is created just fine.
But I can't login no matter how simple or complex I choose the password.

**Comment by zeruniverse** [comment]
Please try the demo, which is currently installed with newest release.

**Comment by nickbe** [comment]
Found it myself.
It seems that password manager has sometimes a problem with https. After changing to http it worked

**Comment by zeruniverse** [comment]
It shouldn't be. The demo is installed with https and actually if you use
http there would be some problems.

For https, you need a valid certificate.

**Comment by nickbe** [comment]
I moved to a different domain and now it works.
Thanks
