### ISSUE TITLE
Different languages

### ISSUE THREAD

**Issue by nickbe** [zeruniverse/Password-Manager#128]
Is there a setting to change the default language? Can we translate some language file somewhere?

**Comment by zeruniverse** [comment]
Currently, no.

**Comment by nickbe** [comment]
Shall I collect all english expressions and make a first translation (english - german) file for you?

**Comment by BenjaminHae** [comment]
I think we should first choose a framework. Then create translation files.

**Comment by nickbe** [comment]
So do you want to switch completely to a framework? password-manager seems small and compact now.
Otherwise why a framework for simple language specific captions?

**Comment by BenjaminHae** [comment]
Because a framework for languages greatly reduces effort needed for implementing different languages and increases maintainability.

**Comment by nickbe** [comment]
Okay. Although I don't see the point here. Don't we talk about simple language files and a simple translation routine?

**Comment by zeruniverse** [comment]
Actually, a framework is not necessary. We only need to translate the UI
and I think there are only a few files containing UI.

**Comment by nickbe** [comment]
Ok then just say the word and I try to contribute some translations for you.
(german, italian, maybe polish)

**Comment by zeruniverse** [comment]
But there's a problem. I think all developments will be in English. So I
don't know how to sync the versions of different languages.

**Comment by zeruniverse** [comment]
Or you can create a new repo and become the maintainer of a language
version. Whenever the main project receives an upgrade, you port it into
your version.

For sure, I'm happy to mention your language version in the main repo.

**Comment by nickbe** [comment]
All we need is a simple function for example lang_txt() which returns the text for the current language, and one lang.<language>.php file per language.

For Example: 
lang.de.php

```
<?php
/* 
-----------------
Language: German
-----------------
*/
$lang = array();
$lang['my website title'] = 'Meine Webseite Titel';
$lang['header title'] = 'Titel der Seite';
$lang['this is our slogan'] = 'Mein Slogan hier';
// Menu
$lang['Home'] = 'Heim';
$lang['Add password'] = 'Neues Passwort';
?>
```

Then all you do is replace all text output with a function call, like this
echo lang_txt('Add password') ;

If the text exists in the does not exist in the language file we simply get the default english text.

**Comment by BenjaminHae** [comment]
I ment a framework just for internationalization. We already use jquery,  bootstrap and crypto js. 
Using an existing framework reduces complexity and keeps the core small and maintainable. I know there are established I18n frameworks for jQuery so why not use one of them? 

Furthermore: Implementing this in php breaks the separation between backend and ui. So please implement it using js.
There should be tools that allow the following:

    <span data-content="foo"></span>

and calling a function in javascript sets the text for every element that has a `data-content` attribute from a config file.

**Comment by BenjaminHae** [comment]
I looked around and propose using https://github.com/jquery-i18n-properties/jquery-i18n-properties
It has good documentation and is mature.
Implementing it should be easy but a bit of work.

**Comment by zeruniverse** [comment]
Great!

**Comment by nickbe** [comment]
Look interesting. Is the language file cached between page refreshes? (Not that it would matter with a small all like this - pure interest)

**Comment by BenjaminHae** [comment]
That should depend on your webserver settings.

**Comment by zeruniverse** [comment]
Any updates?
