### ISSUE TITLE
Cookie issue: Session timed out

### ISSUE THREAD

**Issue by Pofilo** [zeruniverse/Password-Manager#131]
I'm doing some tests on my fork and I have the same issue than in the master branch here.

The problem is that when you connect for the first time on a browser, you are always disconnected with the message:

> Session timed out

The problem obviously comes from the cookie `ServerRenew`. The patch in ~~034aa86377c6b93928677d2674a07f9823ce72ea~~ f93076703d6d6cfc2c634545897a00b35f647198 doesn't seem to solve it.

When you take a look, 2 cookies named `ServerRenew` are created:

+ one with the path `/`
+ the other with the path `/rest/`

Does the problem come from that ?

Thanks and have a nice week :)

**Comment by zeruniverse** [comment]
Check if you have f93076703d6d6cfc2c634545897a00b35f647198

**Comment by Pofilo** [comment]
Yeah, i juste made a `git clone` of `https://github.com/zeruniverse/Password-Manager` so I have it.

Oh, ok I just realize i put the wrong commit in my message, I wanted to say https://github.com/zeruniverse/Password-Manager/commit/f93076703d6d6cfc2c634545897a00b35f647198.

**Comment by zeruniverse** [comment]
Could you try to set the head to that commit and test it again?  I think I tested it after committing f93076703d6d6cfc2c634545897a00b35f647198

**Comment by Pofilo** [comment]
It was working after https://github.com/zeruniverse/Password-Manager/commit/f93076703d6d6cfc2c634545897a00b35f647198.

Tho, the 2 cookies were already created at this moment.

**Comment by zeruniverse** [comment]
Could you try to delete those 2 cookies and try again? or you can use private browsing mode.

@BenjaminHae Please check if your commit 034aa86377c6b93928677d2674a07f9823ce72ea -> e65c8a68a7eb10aece393172a54b77a2056413d8 caused the problem. Thanks!

**Comment by BenjaminHae** [comment]
Found the issue. When the cookie is set by `check.php` it's bound to the path `/rest`. So it can't be found by the javascript as this is executed in `/`.

I'll look into the best way to set it right.

**Comment by zeruniverse** [comment]
Thanks
