### ISSUE TITLE
Could we get rid of the functions in `src/function/encryption.php`?

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#134]
The functions in `encryption.php` are only used on things that are already encrypted on the clientside. Furthermore the key used in those functions is stored alongside the encrypted data. So I don't see a real use in these functions. In my opinion keeping it increases complexity and doesn't really add security.
Would you object to removing it?

**Comment by zeruniverse** [comment]
It can be removed. I think the whole file is from a very old version which does not have client-side encryption.

**Comment by zeruniverse** [comment]
For your question, actually my original thinking was that people get access to the database but not the source code. So even if they get the key and the encrypted data, they don't know how to decrypt it. This function was from a very old version for my own use (before I publish it on GitHub). Yes, if the source code is public, this function does not make sense.
