### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by Pofilo** [zeruniverse/Password-Manager#141]
I have a question about the manager !

I made some modifications on my fork and before the commit https://github.com/zeruniverse/Password-Manager/commit/9898201851a68e22e68208e2ed85137cc6532fca, I was "copying" manually the modifications.
However, the changes since this commit are really important and I don't have time to update my fork.
As there is a lot of security updates, I wonder if the password manager before https://github.com/zeruniverse/Password-Manager/commit/9898201851a68e22e68208e2ed85137cc6532fca is however enough secure to store our passwords ! I guess the answer is yes, but just to be sure if the lasts commits are a must-have.

Thanks for the answer !

**Comment by zeruniverse** [comment]
First, nothing can be 100% secure, even the current version or a future
version.

Your version of Password-Manager is definitely much more secure than most
ways you can think of to manage your passwords. The last few commits are
just to avoid some very extreme cases.

**Comment by Pofilo** [comment]
Yeah of course, nothing can be impenetrable, specially in computer sciences.
However, as I don't have enough knowledge in security, I was unable to figure out if those changes were fundamental.

I will keep my version and eventually make some major security changes.

Thank you very much !
