### ISSUE TITLE
Enhancement clickable URL

### ISSUE THREAD

**Issue by Pofilo** [zeruniverse/Password-Manager#142]
I have an idea for a little enhancement.
When we look at the details of a password, we can eventually see a link. The thing is that we have to copy it manually. I didn't find an easy way to make it clickable :/
Do you have any idea how to do that ?

![capture](https://cloud.githubusercontent.com/assets/7527594/24582684/0e6d2e62-1735-11e7-9ec0-dba904886fd4.PNG)

**Comment by zeruniverse** [comment]
You can add an <a>tag. But people are not necessary to put a URL in the URL
field.

Btw, for me I would usually open the website first and then I try to find
my password.

**Comment by BenjaminHae** [comment]
e65c8a6 adds a button within the accounts table. Maybe that is enough?

**Comment by zeruniverse** [comment]
I think yes.

**Comment by BenjaminHae** [comment]
@pofilo I just(fc0db1a) inserted a hook for the showDetails function, you can now easily implement the functionality yourself.

**Comment by Pofilo** [comment]
Thank you !
I'll check it out ! :)
