### ISSUE TITLE
Unable to export CSV

### ISSUE THREAD

**Issue by zeruniverse** [zeruniverse/Password-Manager#150]
Try here: https://pas.jeffery.cc/

**Comment by zeruniverse** [comment]
I deployed the master branch on my server. It seems your latest few commits break some stuffs.

**Comment by zeruniverse** [comment]
v9.13 has the same bug

**Comment by zeruniverse** [comment]
I think it's caused by ` $.getScript( 'js/lib/jquery.csv.js', function()`

https://github.com/zeruniverse/Password-Manager/blob/master/src/js/main.js#L921

The Content-Security-Policy blocks this line.

**Comment by BenjaminHae** [comment]
Sounds logical. I'll look into it.

**Comment by zeruniverse** [comment]
I think we can make a new page for this

**Comment by zeruniverse** [comment]
* include the csv js file in the new page

**Comment by BenjaminHae** [comment]
I thought about that too (and would very much like this solution). But I think this would take some time to implement because then we should do some refactoring so we wouldn't have too much duplicated code.

The simplest short term solution would be to load the file using the `<script>` tag:
```
<script type="text/javascript" src="js/lib/jquery.csv.js"></script>
```

**Comment by zeruniverse** [comment]
I can do this. Please fix other two bugs

**Comment by zeruniverse** [comment]
The simple solution is not good. This feature is seldomly used but the JS file is 30K+ in size

**Comment by BenjaminHae** [comment]
How about we move the csv export to `recovery.php`? That way we discourage users from doing a cleartext backup while still offering a way to do so?

**Comment by zeruniverse** [comment]
Yes this is a good idea.

**Comment by zeruniverse** [comment]
Import_csv has the same problem
