### ISSUE TITLE
Move version number out of config

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#153]
Could we move the version number out of the config file and into `sqllink.php`?
I think a lot of users just copy their existing config file over the one in the release when they deploy a new version. (I don't I just use `git rebase`) And so their instance doesn't report the version correctly which in a future release might irritate the chrome addon.

**Comment by zeruniverse** [comment]
Sure

**Comment by Pofilo** [comment]
Does it affect the recovery ?
For example when I want to recover an account, the version is at the beginning of backup.txt, will it still be there ?

**Comment by BenjaminHae** [comment]
yes everything still works as before.
