### ISSUE TITLE
Showing loggon attempts problems

### ISSUE THREAD

**Issue by Pofilo** [zeruniverse/Password-Manager#159]
https://github.com/zeruniverse/Password-Manager/pull/144 has some problems.

It works well but introduce some problems when we want to print to information to this information panel.
For example when we add a new password, the label is telling us the entry is correctly added and the second after, refresh itself to tell us again the last login information.

I think that the problem is just because we refresh it. We should maybe add a boolean and only print it on loggin.

**Comment by BenjaminHae** [comment]
Yes you are right. I'll fix it.
