### ISSUE TITLE
confkey and reducedinfo

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#175]
May I remove confkey and reducedinfo? 
They both just seem to add some obscurity which doesn't really increase security. In the case of reducedinfo I even suspect that it reduces the size of the space of possible keys for the pbkdf2 algorithm so in the end we get less entropy for the key and thus make it (a little bit) easier to break.

**Comment by zeruniverse** [comment]
I think when I designed this, I tried to avoid brute-force attack. Users
might use weak login passwords. In this case, even if the attacker logs in,
he doesn't know whether the retrieved password is correct.

**Comment by BenjaminHae** [comment]
As far as I can tell the reducedinfo is used to both authentication and for generating the key, so in case an attacker logs in he automatically has access to everything. For accessing the data it won't make a difference if he has got the correct password or a collision.

**Comment by zeruniverse** [comment]
I think the confkey used the original password.

**Comment by BenjaminHae** [comment]
Confkey is only used in `get_orig_pwd` and `gen_temp_pwd` which look like implementations of the caesar cipher or something related?

**Comment by zeruniverse** [comment]
It's remapping characters in passwords. So the one decrypted from AES is not immediately correct

**Comment by zeruniverse** [comment]
If you have more questions, please reopen it.
