### ISSUE TITLE
Logging out in 'history.php'

### ISSUE THREAD

**Issue by Pofilo** [zeruniverse/Password-Manager#176]
When we are in `history.php`, there is no way to disconnect nor to go to `password.php` again.
Plus, the function `countdown()` of `password.php` doesn't apply in `history.php` so we are not automatically disconnected due to inactivity in `history.php`.

**Comment by zeruniverse** [comment]
But history.php doesn't contain important stuffs. I don't know if this
makes sense...

**Comment by Pofilo** [comment]
It only becomes a security issue if the user forgets to log out and remains on this page.

However, I do agree, it's not a major problem, just wanted to share it to know if we can consider it at something to solve or not.

**Comment by zeruniverse** [comment]
Ok maybe we can add a script letting history.php close itself automatically.

**Comment by BenjaminHae** [comment]
Shouldn't the session get invalidated by the server automatically?

This means the history will still be visible, but reopening the manager is impossible.
The history could/should be considered confidential though so changing this behavior is something we should think about.

**Comment by zeruniverse** [comment]
Yes. The session will be invalid. But as long as you don't refresh the
history page, it will remain there.

**Comment by BenjaminHae** [comment]
As I consider the history at least partially confidential we should consider this.
To reduce duplicated implementations of such timeouts I would suggest embedding the history into the main window as a modal which displays the history.

This is really easy as `history.php` is just using ajax to display the information already.

**Comment by zeruniverse** [comment]
Yes. I'll do it when I have time

**Comment by BenjaminHae** [comment]
@zeruniverse what do you think about migrating to angularJS?
I've experimented a bit with it and I think there are a lot of things that get really easy and a lot more readable than they are now. If you think that's a viable option you could wait changing this until we do it during the transition.

**Comment by zeruniverse** [comment]
Never used angularJS before… Will take a look

**Comment by BenjaminHae** [comment]
[Here's a quick and very rough implementation for the history page](https://github.com/BenjaminHae/Password-Manager/tree/angular). Not fully functional but you can see the important changes.

**Comment by zeruniverse** [comment]
Thanks!
