### ISSUE TITLE
Integrating recaptcha and email verification

### ISSUE THREAD

**Issue by GitGoppy** [zeruniverse/Password-Manager#177]
I want to integrate recaptcha and email verification into the password manager, how do i do this?

**Comment by zeruniverse** [comment]
Simple three steps...

+ In `/src/index.php`, do modification to `html` (add input field for recaptcha etc...)
+ In `/src/js/index.js`, search for `$("#loginform").on('submit',function(e)`, edit this function by adding the post field (you want to post the new values to backend...)
+ In `/src/rest/check.php`, check the validity of additional authentication, let `check.php` die before setting session values if those additional stuff is not correct.

For sending emails, you might need another php file to send email and set `$_SESSION['email_captcha]`, then you can check if `$_SESSION['email_captcha] == $_POST['email_code]` in `check.php`
