### ISSUE TITLE
Issue added with pbkdf2 (PIN not working)

### ISSUE THREAD

**Issue by Pofilo** [zeruniverse/Password-Manager#180]
An issue has been added with the commit: https://github.com/zeruniverse/Password-Manager/commit/0b563510e76cfb93aacec0abf56b348317bd7e94
Before the commit, the PIN used to work, after, it doesn't (when you try to login with the PIN code, the PIN is blocked as if a wrong PIN was tried 3 times).

I don't really have time to look after this right now, but at least the bug is known :)
(bug reproduced on the demo)

**Comment by BenjaminHae** [comment]
I'll look into it. Probably this weekend.

**Comment by BenjaminHae** [comment]
First report: It's something on the frontend. The backend behaves perfectly well.

**Comment by BenjaminHae** [comment]
Could you please check if it works for you?

**Comment by Pofilo** [comment]
Yes, it is working again, thanks :)
