### ISSUE TITLE
additional custom fields on add entry

### ISSUE THREAD

**Issue by w112nxs** [zeruniverse/Password-Manager#187]
Apart from passwords, I do have certain accounts which has secondary credentials. Wondering if there is an easy way to add more entries into the "add entry" page.

**Comment by Pofilo** [comment]
Lucky you are, there is already this option in the application :)

I let you see this page: [https://github.com/zeruniverse/Password-Manager/wiki/Advanced-Features](https://github.com/zeruniverse/Password-Manager/wiki/Advanced-Features)

You can set it in the conf file for every user or put `$CUSTOMIZE_FIELDS` at true to allow users to change it individually !

**Comment by zeruniverse** [comment]
Already implemented!
