### ISSUE TITLE
Upgrade to 9.15

### ISSUE THREAD

**Issue by Pofilo** [zeruniverse/Password-Manager#189]
Hello ! 

I wanted to use the scripts to upgrade to 9.15 from 9.13 but I have an issue.

[https://github.com/BenjaminHae/Password-Manager/blob/upgrades/upgrade_9.13_remove_Encryption.php](https://github.com/BenjaminHae/Password-Manager/blob/upgrades/upgrade_9.13_remove_Encryption.php)
and [https://github.com/BenjaminHae/Password-Manager/blob/upgrades/upgrade_9.15_pbkdf.php](https://github.com/BenjaminHae/Password-Manager/blob/upgrades/upgrade_9.15_pbkdf.php)

The first script works well, databases are correctly updated.
The second seems to work well too (passwords in `pwdusrrecord` seems to be generated again).

However, I can't connect to the manager after that, saying me that the password is incorrect.

I executed the script with the conf and files of 9.15 to have `$PBKDF2_ITERATIONS = 64000;`.

I don't really know what I'm doing wrong :/

If you guys have an idea :)
Otherwise, I'll use the backups but as we are severals users, it will be complicated :/

**Comment by Pofilo** [comment]
After some analysis on [upgrade_9.13_remove_Encryption.php](https://github.com/BenjaminHae/Password-Manager/blob/upgrades/upgrade_9.13_remove_Encryption.php) I found the problem.

First, I was logging `GLOBAL_SALT_3` and then `newpwd` which was null.

The problem is just some typo on line 61 and 62:
We have to replace this:
```    
$newpwd=$i['pwd'];
$newpwd = decrypt($i['pwd'],$GLOBAL_SALT_3);
```
by this
```
$newpwd=$i['password'];
$newpwd = decrypt($i['password'],$GLOBAL_SALT_3);
```

And to see that `pwd` should be `password` is quite a challenge ^^

Anyway, @BenjaminHae , do you want me to make a pull request on the script ?

And by the way, the scripts provided in [RELEASE](https://github.com/zeruniverse/Password-Manager/releases/download/9.15/upgrade.zip) are correct.

**Comment by BenjaminHae** [comment]
It would be really cool if you could create the pull request.
I vaguely remember this issue but don't remember why we just fixed release, not master.

**Comment by Pofilo** [comment]
https://github.com/BenjaminHae/Password-Manager/pull/48
