### ISSUE TITLE
Printing showMessage

### ISSUE THREAD

**Issue by Pofilo** [zeruniverse/Password-Manager#197]
https://github.com/zeruniverse/Password-Manager/pull/194  introduces a little regression for printing the message `Login failed: AUTHENTICATION ERROR, PLEASE RELOGIN`.

![image](https://user-images.githubusercontent.com/7527594/36275516-5c336de4-128b-11e8-9306-fb56b45a9411.png)

You can simply reproduce the _bug_ accessing `/password.php` while not connected.

I don't have enough time to investigate, but I think it is just little stuff.

**Comment by BenjaminHae** [comment]
thanks. Javascripts `decodeURIcomponent` behaves a bit weird as it doesn't handle `+` as one would expect.
