### ISSUE TITLE
Unable to access signup.php from AWS Instance 

### ISSUE THREAD

**Issue by tusharjambhekar** [zeruniverse/Password-Manager#202]
I have enabled AWS RDS(MySql)  VM can able to access webpage but unable to access link for signup.php.

![image](https://user-images.githubusercontent.com/25099285/37525160-06c0dd8c-2952-11e8-8dad-e04543ab6e48.png)

**Comment by Pofilo** [comment]
In the file `src/function/config.php`, make sure you have `$ALLOW_SIGN_UP` setted at `true`.

**Comment by BenjaminHae** [comment]
> In the file src/function/config.php, make sure you have $ALLOW_SIGN_UP setted at true.

This is the default value... Weird.

@tusharjambhekar  Could you please open the "Network" tab or similar in the developer tools of your browser, reload the page and show us the content of the response of "info.php" when opening the signup page? (Make sure to remove private details like host domain).

**Comment by BenjaminHae** [comment]
@tusharjambhekar To pin down the problem: is the "signup" button visible on the login page?

**Comment by tusharjambhekar** [comment]
In the file src/function/config.php, make sure you have $ALLOW_SIGN_UP setted at true is True
![image](https://user-images.githubusercontent.com/25099285/37534265-608ca68a-296a-11e8-89e4-f5e72ed92879.png)

**Comment by tusharjambhekar** [comment]
"Network" tab from the developer tools


![image](https://user-images.githubusercontent.com/25099285/37534424-d07e18d4-296a-11e8-80bb-18c122d0ddc7.png)

**Comment by BenjaminHae** [comment]
The request provokes an error on your webserver. You should check your logs for more information.

**Comment by tusharjambhekar** [comment]
I am unable to find any logs at apache as well as at mysql, nothing coming

**Comment by BenjaminHae** [comment]
Then it's nearly impossible to pin it down.

**Comment by tusharjambhekar** [comment]
I am getting below unusual error message at /httpd/error_log


![image](https://user-images.githubusercontent.com/25099285/37535586-29e7f414-296e-11e8-9a06-6c66e8e66c53.png)

**Comment by BenjaminHae** [comment]
Can you please provide the specified line from the file in your installation? I can't see anything wrong in this file in the repo.

**Comment by zeruniverse** [comment]
To get a ‘signup not allowed’ message, the php backend should return a
‘method not allowed’ message (not anything else). And this message will
only be returned if $ALLOW_SIGNUP is false.

Looks very weird to me.

**Comment by tusharjambhekar** [comment]
How to troubleshoot from this

![image](https://user-images.githubusercontent.com/25099285/37556188-6ee9cb8c-2a18-11e8-91d5-114e3d42947b.png)


![image](https://user-images.githubusercontent.com/25099285/37556198-9eae393e-2a18-11e8-97d9-fccd9c07a703.png)

**Comment by BenjaminHae** [comment]
You need to show us your webservers error log. The access log is not enough to figure it out.

**Comment by zeruniverse** [comment]
And if you don’t mind:

1. Please provide the password manager login address of your AWS instance

2. Please paste your Apache error log, it would contain PHP error

**Comment by zeruniverse** [comment]
* You can save the error log as a txt file and upload to Github issues.

**Comment by tusharjambhekar** [comment]
1. ec2-54-226-202-102.compute-1.amazonaws.com/signup.php
2. [root@passmanager ec2-user]# tail -f /var/log/httpd/error_log
[Sat Mar 17 13:48:04 2018] [error] [client 103.224.156.138] PHP Parse error:  syntax error, unexpected '[' in /var/www/html/rest/info.php on line 28, referer: http://passmanager.ml/signup.php
[Sat Mar 17 13:48:05 2018] [error] [client 103.224.156.138] File does not exist: /var/www/html/css/bootstrap.min.css.map
[Sat Mar 17 13:49:08 2018] [error] [client 103.224.156.138] PHP Parse error:  syntax error, unexpected '[' in /var/www/html/rest/info.php on line 28
[Sat Mar 17 13:49:20 2018] [error] [client 103.224.156.138] PHP Parse error:  syntax error, unexpected '[' in /var/www/html/rest/info.php on line 28, referer: http://passmanager.ml/signup.php
[Sat Mar 17 13:49:21 2018] [error] [client 103.224.156.138] File does not exist: /var/www/html/css/bootstrap.min.css.map
[Sat Mar 17 13:50:20 2018] [error] [client 103.224.156.138] PHP Parse error:  syntax error, unexpected '[' in /var/www/html/rest/info.php on line 28, referer: http://passmanager.ml/signup.php
[Sat Mar 17 13:50:21 2018] [error] [client 103.224.156.138] File does not exist: /var/www/html/css/bootstrap.min.css.map
[Sat Mar 17 13:57:23 2018] [error] [client 103.224.156.138] PHP Parse error:  syntax error, unexpected '[' in /var/www/html/rest/info.php on line 28, referer: http://passmanager.ml/
[Sat Mar 17 13:57:29 2018] [error] [client 103.224.156.138] PHP Parse error:  syntax error, unexpected '[' in /var/www/html/rest/info.php on line 28, referer: http://passmanager.ml/
[Sat Mar 17 17:20:47 2018] [error] [client 183.83.212.166] PHP Parse error:  syntax error, unexpected '[' in /var/www/html/rest/info.php on line 28, referer: http://ec2-54-226-202-102.compute-1.amazonaws.com/signup.php

**Comment by tusharjambhekar** [comment]
Hi ,
If you there free I can give you access of AWS instance.

**Comment by tusharjambhekar** [comment]
I am trying to browse from Linux text-browser there also I am getting the following issue
![image](https://user-images.githubusercontent.com/25099285/37558223-a3da7ea4-2a36-11e8-8177-a432d183d402.png)

**Comment by BenjaminHae** [comment]
Can you please provide the specified line from your local file named in the error log in your installation? I can't see anything wrong in this file in the repo.

**Comment by tusharjambhekar** [comment]
Yes I know nothing wrong in the repo but then also don't know what is this error.

[Sat Mar 17 17:20:47 2018] [error] [client 183.83.212.166] PHP Parse error: syntax error, unexpected '[' in /var/www/html/rest/info.php on line 28, referer: http://ec2-54-226-202-102.compute-1.amazonaws.com/signup.php



![image](https://user-images.githubusercontent.com/25099285/37558328-54b63b0e-2a38-11e8-8554-b5680a2a02c7.png)

**Comment by BenjaminHae** [comment]
Which php version is installed?

**Comment by tusharjambhekar** [comment]
It's php56.x86_64

**Comment by BenjaminHae** [comment]
Could you try switching to php 7?

**Comment by tusharjambhekar** [comment]
Yes , I am going to do it right now only ... thinking of that

**Comment by tusharjambhekar** [comment]
Upgraded php version to 7 
can able to login to signup page but now getting as error " Hostdomain mismatch. Please check your config file."


![image](https://user-images.githubusercontent.com/25099285/37558525-5efa6f88-2a3b-11e8-929c-ce9bdf79afc5.png)

**Comment by BenjaminHae** [comment]
Yes, please check your config, especially this line:
//This is to prevent cross-site attacks. If $HOSTDOMAIN is not the prefix of HTTP_REFERER string, an exception will be raised.
$HOSTDOMAIN...

**Comment by zeruniverse** [comment]
I'm using PHP5.6 as well and I can run password-manager smoothly. Weird...

But anyway, after editing $HOSTDOMAIN, you will be able to use it

**Comment by tusharjambhekar** [comment]
I have done changes at config.php then also giving the error .


![image](https://user-images.githubusercontent.com/25099285/37563361-0a8c54c4-2aa5-11e8-8363-c678c938e3bb.png)

**Comment by Pofilo** [comment]
According to the `README` file: 

> From v9.13, Password-Manager only supports HTTPS

Plus, `$HOSTDOMAIN` must be exact ! So you have to set up the HTTPS to make it work.

**Comment by zeruniverse** [comment]
An alternative is to set $HOSTDOMAIN to http:// instead of https://. Though
this is not tested. Finally you will need https to keep your password safe

**Comment by tusharjambhekar** [comment]
Thanks http:// working but I will configure web server to run on ssl .

**Comment by zeruniverse** [comment]
@tusharjambhekar I want to figure out why PHP 5.6 doesn't work. Could you compare your phpinfo() page with mine?

Mine is here: https://secure.zzeyu.com/

**Comment by tusharjambhekar** [comment]
Hi I have already uninstalled the old version of PHP.
