### ISSUE TITLE
Can we migrate MySQL to Amazon Aurora

### ISSUE THREAD

**Issue by tusharjambhekar** [zeruniverse/Password-Manager#203]
I want to host DB at AWS  Aurora it is possible? for this do I need to make any changes.

**Comment by BenjaminHae** [comment]
It looks as if it supports mysql like queries. 
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Aurora.AuroraMySQL.html
So just try it.

**Comment by tusharjambhekar** [comment]
Thank you. I will check and update.

**Comment by tusharjambhekar** [comment]
Can I try this  : http://www.treselle.com/blog/mysql-to-amazon-aurora-diverse-ways-of-data-migration/

**Comment by BenjaminHae** [comment]
I can't see why not.

**Comment by zeruniverse** [comment]
closed due to inactivity.
