### ISSUE TITLE
PIN error

### ISSUE THREAD

**Issue by GitGoppy** [zeruniverse/Password-Manager#205]
If a pin is set on a user account after some time the password manager stops working and no user can log in. The password manager restores function when pin is deleted.

**Comment by zeruniverse** [comment]
Sorry. Could you give more details? Like what kind of error you saw

The PIN should be user-specific and one user setting a PIN shouldn’t have
any impact on another user.

**Comment by Pofilo** [comment]
A PIN is active only 90 days, after that, you have to configure it again.
However, your problem looks different, you should give us more explanations how to reproduce the bug.

**Comment by GitGoppy** [comment]
My error, the error is not caused by a pin set, it is caused when the user gets logged out for inactivity, the sign up button dissapears and you can't login, but there is no message that the user was logged out except what is shown in the url

**Comment by GitGoppy** [comment]
No, wait, the password manager breaks at random intervals, i get invalid method error

**Comment by GitGoppy** [comment]
The bug was not present before, it appeared just now

**Comment by GitGoppy** [comment]
The error seems to appear only in chrome right now

**Comment by GitGoppy** [comment]
I have a theory, the password manager doesn't allow any login attempts after a brute force attack?

**Comment by GitGoppy** [comment]
Nevermind, it's not an application error, it's rocket loader external application
