### ISSUE TITLE
PHP Fatal error:  Arrays are not allowed as constants

### ISSUE THREAD

**Issue by zeruniverse** [zeruniverse/Password-Manager#206]
[Wed Jul 25 06:22:14.702426 2018] [:error] [pid 10018] [client 127.0.0.1:45772] PHP Fatal error:  Arrays are not allowed as constants in /home/project-web/phppasswordmanager/htdocs/function/ajax.php on line 26, referer: https://phppasswordmanager.sourceforge.io/

Constant array is only supported for PHP 5.6+. Is there any alternative implementation that comply with older version PHP?

**Comment by BenjaminHae** [comment]
We can just remove the const keyword for the demo.

**Comment by BenjaminHae** [comment]
We explicitly need php 5.5+ for pbkdf, there must be a way to deploy the application to sourceforge with a newer php version. Especially since 5.4 and 5.5 are not supported anymore.

**Comment by zeruniverse** [comment]
We stated PHP 5.5+ is needed but const array is not available until 5.6.
Sourceforge uses 5.4 and I commented out pbkdf

**Comment by BenjaminHae** [comment]
Mh, weird that the [ci checks](https://travis-ci.org/zeruniverse/Password-Manager/jobs/408130808) don't fail on php 5.5...

**Comment by zeruniverse** [comment]
http://php.net/manual/en/language.constants.syntax.php

**Comment by zeruniverse** [comment]
Ok Let’s change php requirement to >5.6
