### ISSUE TITLE
Could not write to clipboard

### ISSUE THREAD

**Issue by zeruniverse** [zeruniverse/Password-Manager#207]
Linux: Chromium.

Do you know which browsers are supported?

**Comment by BenjaminHae** [comment]
Chrome from version 61. So newer chromium versions should be covered. I'll implement a check in the plugin that hides the icon when the necessary interface is not implemented.

**Comment by zeruniverse** [comment]
Safari (iOS) can’t copy as well

**Comment by BenjaminHae** [comment]
Yes it's only Chrome that has implemented [the standard](https://w3c.github.io/clipboard-apis/#clipboard-interface) yet. 
The plugin now checks for the availability of the interface and only shows the button when it's there.
