### ISSUE TITLE
Check demo site

### ISSUE THREAD

**Issue by zeruniverse** [zeruniverse/Password-Manager#208]
sourceforge uses php 5.4 so some workaround was done to make sure demo runs properly. 

With simple checks, it works fine but I don't know the exact changes you made so it's better you test it again.

https://phppasswordmanager.sourceforge.io/

**Comment by BenjaminHae** [comment]
Do you have a diff of the source files for me?

**Comment by zeruniverse** [comment]
I just removed all pbkdf2 and removed the const keyword.

**Comment by BenjaminHae** [comment]
Then everything should be fine.
