### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by shancept** [zeruniverse/Password-Manager#211]
![image](https://user-images.githubusercontent.com/25472994/44098830-5fbbb508-a00b-11e8-8e13-050dae1d3f52.png)
Here is my mistake

**Comment by zeruniverse** [comment]
Support for HTTP has dropped since 9.13. In order to use PWManager, you must turn on SSL and use https protocol

**Comment by shancept** [comment]
Even on the local host?  14.08.2018, 21:35, "Jeffery Zhao" <notifications@github.com>:Support for HTTP has dropped since 9.13. In order to use PWManager, you must turn on SSL and use https protocol—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by zeruniverse** [comment]
Yes.

Follow this: https://github.com/zeruniverse/Password-Manager/wiki/Installation

**Comment by shancept** [comment]
It is a pity( but anyway thank you very much for the answer! 14.08.2018, 21:39, "Jeffery Zhao" <notifications@github.com>:Yes.Follow this: https://github.com/zeruniverse/Password-Manager/wiki/Installation—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by zeruniverse** [comment]
Your local malicious software will know your password if it injects bad JavaScript and makes your password unsafe.

**Comment by zeruniverse** [comment]
Why you said it’s a pity? Enabling HTTPS should be very simple in local. And you just need to add an exception in your browser.

**Comment by shancept** [comment]
And how to do it? 14.08.2018, 21:45, "Jeffery Zhao" <notifications@github.com>:Why you said it's a pity? Enabling HTTPS should be very simple in local. And you just need to add an exception in your browser.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by zeruniverse** [comment]
You can google.

**Comment by BenjaminHae** [comment]
There is no explicit check for using tls. But every cookie is stored so that it's only sent with encrypted connections.

I think it would be enough to just set the url in the config to http, but I'm not sure.

**Comment by BenjaminHae** [comment]
If this is not working it's probably because the session cookie is stored in a way that it only gets sent when using encrypted connections. You can change that in the last line of '/src/function/sqllink.php'. You probably need to also change that for every call to `setcookie`.

**Comment by BenjaminHae** [comment]
Btw: This seems to be an easy solution for setting up local certificates for development environments: https://github.com/FiloSottile/mkcert
