### ISSUE TITLE
Keep 1 or 2 or all history passwords

### ISSUE THREAD

**Issue by zeruniverse** [zeruniverse/Password-Manager#214]
For password recovery (if you lose all phones etc.), some websites ask for history password.

**Comment by BenjaminHae** [comment]
That's a perfect use case for a plugin.

**Comment by BenjaminHae** [comment]
I've started a [plugin implementing this](/BenjaminHae/Password-Manager/tree/passwordHistory). It's untested but a nice starting point. It already stores old passwords when setting a new one. The missing part is displaying this information. Where would you like to have it displayed? I think doing this is a nice exercise to get to now the plugin architecture.

It currently does not use the same encryption as for the password (it uses the encryption for all other account info, i.e. aes...). Implementing the additional "encryption" would add a lot of complexity I'm scared of implementing.

**Comment by zeruniverse** [comment]
So all fields starting with `_` is invisible to users right?

**Comment by BenjaminHae** [comment]
Yes, they are hidden by default but can be displayed by a plugin. Best example is the passwordage plugin.
