### ISSUE TITLE
Doesn't work on new Chrome or Chromium

### ISSUE THREAD

**Issue by zeruniverse** [zeruniverse/Password-Manager#217]
Version: 68.0.3440.106

Try it here: [phppasswordmanager.sourceforge.io](https://phppasswordmanager.sourceforge.io)

after login, stuck at PLEASE WAIT WHILE WE ARE DECRYPTING YOUR PASSWORD...

No errors (everything 200) at the network tab of the developer tool. And nothing pending. It's like ajax is not trigged.

**Comment by zeruniverse** [comment]
Firefox and microsoft edge works.

**Comment by zeruniverse** [comment]
[9.15](https://github.com/zeruniverse/Password-Manager/releases/tag/9.15) has no problem

**Comment by BenjaminHae** [comment]
Hehe, that's not a chrome bug.
It's because of my addon 😄 
Disable it and it will work.

**Comment by BenjaminHae** [comment]
I think the check if it's on the right domain doesn't work properly. I'll look into it.

But nice to know you are using it 😄

**Comment by zeruniverse** [comment]
could you update your plugin to avoid this from happening?

**Comment by BenjaminHae** [comment]
It's updated. Might take some time till it is updated on your machine.

**Comment by zeruniverse** [comment]
Did you make it work? If yes, we can make a 10.01 release.

**Comment by BenjaminHae** [comment]
Yes, but it only required changes in the addon, not the password manager itself. So there's currently no need for a new release. I'll open one PR this weekend where a new release will make sense.
