### ISSUE TITLE
Hide passwords in edit dialog

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#222]
I propose this way:
When you open the dialog the password is not visible:
![image](https://user-images.githubusercontent.com/7386033/46550732-2d197600-c8d6-11e8-96dc-95d674579618.png)
Entering a password or(!) clicking the generate new password button shows the input/generated password hidden:
![image](https://user-images.githubusercontent.com/7386033/46550855-8681a500-c8d6-11e8-9d87-2ae03dfe5826.png)
Clicking the eye-button shows the password (when there is text in the input):
![image](https://user-images.githubusercontent.com/7386033/46550903-a87b2780-c8d6-11e8-805c-75b90847d877.png)
If there is no text and the button is pressed, the old password will be shown in plain.

Whenever the eye-button is clicked it changes to a hide button and clicking it changes the input to a password input so that the password is hidden again.

There is one issue though. This won't work anymore:
![image](https://user-images.githubusercontent.com/7386033/46550979-d6606c00-c8d6-11e8-83d3-e0de1ed81f5c.png)
Should we introduce an additional button that get's you the old password back or should the hint be shown on the dismiss button?
![image](https://user-images.githubusercontent.com/7386033/46551051-03148380-c8d7-11e8-874a-8c165d411d6e.png)

@Pofilo

**Comment by Pofilo** [comment]
That's a good question yeah !
Maybe a third button would be easier to understand for someone who doesn't know how it works.

Seeing the old password seems important to me.
