### ISSUE TITLE
Improve error message if DB schema has not been imported yet

### ISSUE THREAD

**Issue by schams-net** [zeruniverse/Password-Manager#228]
I understand, this is a configuration error caused by the administrator when setting up an instance. However, a more meaningful error message would be beneficial, if the DB schema file `initial.sql` has not been imported yet.

![screenshot0001](https://user-images.githubusercontent.com/3617721/51006074-ac81aa00-1595-11e9-899a-938c757af734.png)

**Comment by zeruniverse** [comment]
@BenjaminHae I remembered you once did it.

**Comment by BenjaminHae** [comment]
I'll look into it when I have time

**Comment by zeruniverse** [comment]
Goto #248 if not been done yet
