### ISSUE TITLE
Missing header bar on "Account Activity" page

### ISSUE THREAD

**Issue by schams-net** [zeruniverse/Password-Manager#229]
When accessing the account activity view (`https://example.com/history.php`), the page does not show the header bar. As a result, the UI does not offer a way to go back to the _main_ page. The only option is the back button in your browser.

**Comment by zeruniverse** [comment]
If my memory works, this page should open in a new window. So you can
simply close the window and the main page will remain on the old window.

**Comment by schams-net** [comment]
Maybe this is browser-related, but for me, it opens in the same window.
Firefox 60.4.0esr (64-bit) under Debian GNU/Linux with commit e749c010d28d7a1c276096cd8c7c8355d1df820b

![screenshot0001](https://user-images.githubusercontent.com/3617721/51006995-d210b280-1599-11e9-8622-424b080571fa.png)

**Comment by BenjaminHae** [comment]
I'm planning to integrate this page more into the main page. But this will be part of some bigger changes that will happen someday.
