### ISSUE TITLE
Linebreaks in fields should be forbidden or replaced

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#23]
If you insert a linebreak when customizing fields the javascript code can't be executed because there will be a linebreak in a string literal.

**Comment by zeruniverse** [comment]
There'll be tons of cases that user can make this fields broken. I think as
long as it can be JSON.parse(), we can take it.

For linebreak, I'll remove the new line or space at the end or beginning.

**Comment by BenjaminHae** [comment]
Problem is: If you change fields to contain a linebreak, everything is broken. You can't access your account and change it back.

**Comment by zeruniverse** [comment]
I realized it. I think just need to remove all spaces and new lines at the
beginning or end.

Is it right?

**Comment by BenjaminHae** [comment]
The way I would prefer is removing the linebreaks when reading the fields from the database. But only the first time, not when reading them for the textarea. That way the user may format it nicely.

**Comment by zeruniverse** [comment]
Fixed by 5fbe322ef65681731fe1a4d2da3d5704f2b7b532
