### ISSUE TITLE
Proposal: clipboard JS library with better browser support

### ISSUE THREAD

**Issue by schams-net** [zeruniverse/Password-Manager#230]
I understand that Password-Manager currently uses the [Clipboard Interface](https://w3c.github.io/clipboard-apis/#clipboard-interface) to copy passwords to the clipboard. However, this is only supported by Chrome.

It would be nice to use a library that features better browser support.
For example: https://zenorocha.github.io/clipboard.js

Related #207

**Comment by BenjaminHae** [comment]
It seems like ff supports the clipboard Interface: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API
I'll make the changes so that Firefox is supported when I have time.

**Comment by BenjaminHae** [comment]
What browser are you using? It works for me when using a current firefox.

**Comment by schams-net** [comment]
Firefox 60.4.0esr (default package in [Debian 9](https://packages.debian.org/stretch/firefox-esr)).

![screenshot0001](https://user-images.githubusercontent.com/3617721/51150497-a6a00780-18ba-11e9-83db-0380ba82058b.png)

**Comment by zeruniverse** [comment]
Goto #248 if not done yet
