### ISSUE TITLE
[Enhancement] Introduce DBAL to make application database-independent

### ISSUE THREAD

**Issue by schams-net** [zeruniverse/Password-Manager#232]
## Problem

A MySQL/MariaDB database instance is currently a mandatory requirement for the application. Other DB servers such as PostgreSQL, MSSQL, etc. can not be used.

## Suggested Solution

A database abstraction layer (DBAL) such as [Doctrine](https://www.doctrine-project.org/) would make the application independent from a specific database engine. This approach would also make it possible to use server-less engines such as [SQLite](http://sqlite.org/) (a DB engine embedded in PHP), which would mean no separate database server is required on the server.

## Changes Required

* Select and add DBAL (e.g. "Doctrine", see below).
* Rework all SQL statements to use the concrete PDO API.
* Consider an alternative of importing `initial.sql`.

## Additional Notes

[Doctrine](https://www.doctrine-project.org/) is a well-know DBAL in the PHP world today. Currently supported database vendors include MySQL, Oracle, Microsoft SQL Server, PostgreSQL, SAP Sybase SQL Anywhere, SQLite and Drizzle.

**Comment by CoderJason123** [comment]
Not a bad idea -- i actually ran on sqlite just to see how painful it would be, and it worked quite well, just a few data type issues.  My only comment to add would be to please keep the code base small.  It's easy for folks to look thru all the code and feel comfortable.

**Comment by BenjaminHae** [comment]
I'll upload my first steps in moving to doctrine this weekend.

**Comment by BenjaminHae** [comment]
I've tried to implement the backend based on the symfony framework with doctrine as orm.
It is in no way complete and does not conform to the interfaces used in the current version.
https://github.com/BenjaminHae/Password-Manager/tree/new-backend

Maybe someone might look into it and review whether this is a good idea.
Pros:
- Use proven frameworks
- Ease of extending (see plugins)
- Possibility of using existing libraries for complex problems (for example 2FA, OAuth, ...)
- defined interfaces using OpenAPIDescription, makes it a lot easier to write different clients (mobile apps)
Cons:
- much bigger codebase, not as easy to review

**Comment by zeruniverse** [comment]
GOTO #248 if not done yet
