### ISSUE TITLE
[Enhancement] Allow installation via PHP Composer

### ISSUE THREAD

**Issue by schams-net** [zeruniverse/Password-Manager#233]
## Problem

While not overly complicted, the [installation process](https://github.com/zeruniverse/Password-Manager/wiki/Installation) requires some manual steps. Also, some dependent libraries are currently stored "hard-coded" in the project folder.

## Suggested Solution

[Composer](https://getcomposer.org/) is a widely used PHP dependency management solution that simplifies the installation and ongoing updates of PHP projects and their dependencies.

## Changes Required

* Develop a central control file `composer.json`.
* Restructure folders (e.g. Composer creates a `vendor/` directory).
* Update references to libraries (new paths.).

**Comment by BenjaminHae** [comment]
Can be done within the course of #235.

**Comment by zeruniverse** [comment]
Goto #248
