### ISSUE TITLE
[Enhancement] Update Bootstrap to version 4.2+

### ISSUE THREAD

**Issue by schams-net** [zeruniverse/Password-Manager#234]
## Problem

The application currently uses [Bootstrap version 3.3.7](https://getbootstrap.com/docs/3.3/). Further development on Bootstrap v3 has been stopped and a stable version of Bootstrap v4 was released in January 2018. The new version is a major rewrite from Bootstrapv 3 with significant changes and improvements.

## Suggested Solution

Update Bootstrap to [version 4.2](https://getbootstrap.com/docs/4.2/) or newer.

## Changes Required

* Remove Bootstrap v3 files from the repository.
* Include Bootstrap files from an external source.
* Rewrite HTML code to use Bootstrap v4 specific code and layout.

## Risks and Dependencies

Some JavaScript/CSS library currently used possibly depend on a specific version of Bootstrap. It needs to be assessed, if they are either compatible with Bootstrap v4 or need to be updated or replaced.

## Additional Notes

It is assumed, it is ok, if the Bootstrap files are included into the web interface by using their external reference (typically a CDN such as `stackpath.bootstrapcdn.com` and/or `cloudflare.com`). **Subresource Integrity** (SRI) should be used as a security feature in this case.

* https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
* https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/

**Comment by Pofilo** [comment]
Having external dependencies can be a real problem. For example on an instance which does not have access to the internet.
My point is also valid for #233.

**Comment by BenjaminHae** [comment]
I'd be happy to accept a pr that changes the framework to bootstrap 4. 
But I strongly oppose loading any external resources.

**Comment by schams-net** [comment]
Understood your point re external resources. I am happy to have a look what is required to update Bootstrap to v4 and create a PR once completed and tested.

However, it makes sense to deal with that after #235 and #236 have been resolved (and are in `master`).

**Comment by zeruniverse** [comment]
Goto #248
