### ISSUE TITLE
Follow PSR-2 Coding Standards

### ISSUE THREAD

**Issue by schams-net** [zeruniverse/Password-Manager#236]
```
$ phpcs --report=summary --standard=PSR2 --extensions=php .
```
```
PHP CODE SNIFFER REPORT SUMMARY
---------------------------------------------------------------
FILE                                           ERRORS  WARNINGS
---------------------------------------------------------------
Password-Manager/src/index.php                 0       7
Password-Manager/src/signup.php                3       1
Password-Manager/src/history.php               4       0
Password-Manager/src/function/sqllink.php      0       3
Password-Manager/src/function/ajax.php         0       1
Password-Manager/src/function/config.php       0       2
Password-Manager/src/recovery.php              1       5
Password-Manager/src/password.php              0       27
Password-Manager/src/rest/info.php             0       1
Password-Manager/src/rest/changeuserpw.php     0       2
Password-Manager/src/rest/setpin.php           0       1
Password-Manager/src/rest/history.php          0       1
Password-Manager/src/rest/check.php            0       4
Password-Manager/src/rest/backup.php           0       1
Password-Manager/src/rest/password.php         0       1
---------------------------------------------------------------
A TOTAL OF 8 ERRORS AND 57 WARNINGS WERE FOUND IN 15 FILES
---------------------------------------------------------------
```

**Comment by BenjaminHae** [comment]
Do you know a linter we could integrate in the buildchain at github?

**Comment by schams-net** [comment]
I use [PHP CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) by Squiz Labs in my local IDE, that _forces_ my to write code that complies with PSR-2. I use the same tool in my self-hosted GitLab CI/CD build process, but I am not aware of anything for GitHub (at least not for free).

PS: is there a reason why you closed this issue without merging [PR 238](https://github.com/zeruniverse/Password-Manager/pull/238)? Rejected or accidentally closed? :-)

**Comment by BenjaminHae** [comment]
Oh I'm Sorry, closed by accident

**Comment by BenjaminHae** [comment]
Your issues and PRs are not forgotten :)
I'm currently working on moving everything to symfony4, which addresses #235, #232 and possibly #239 and #226.
When this is done the code should be a lot easier to read. Implementing new features should be a lot easier too.
If you've got small changes go ahead and do them, I'll take care of merging them to the new architecture.
