### ISSUE TITLE
Read maximal file size for uploads from PHP configuration

### ISSUE THREAD

**Issue by schams-net** [zeruniverse/Password-Manager#237]
In file `password.php`, a hard-coded value claims that the (quote) "_Maximal file size allowed is 3MB._". However, this depends on the PHP configuration `upload_max_filesize` at least.

The value should be read from the configuration to be more accurate.

**Comment by BenjaminHae** [comment]
I think the value could be additionally limited by the php configuration. A per application limit should still be possible.

**Comment by zeruniverse** [comment]
Close due to inactivity. For new features, please submit MR to the new project. #248
