### ISSUE TITLE
[Enhancement] Allow for extensions without changing core code

### ISSUE THREAD

**Issue by schams-net** [zeruniverse/Password-Manager#239]
## Problem

The documentation (file `README.md`) reads:

> _You can easily add E-mail verification, Google authentication... in your version of password manager. Put your implementation inside `src/rest/check.php`, which is used for login authentication._

This encourages users to edit a core file, which -- when application is updated -- is overwritten from the file from the repository.

## Suggested Solution

Change application to allow users to extend functionality, without the need to chance core files. For example by introducing a Signals/Slots concept.

**Comment by zeruniverse** [comment]
Is this done?

**Comment by BenjaminHae** [comment]
It's part of the complete rewrite. But not implemented yet.

**Comment by zeruniverse** [comment]
For new feature, goto #248
