### ISSUE TITLE
Enable Group by Tags default

### ISSUE THREAD

**Issue by axiades** [zeruniverse/Password-Manager#241]
Hello,

i want to have the Group by Tags function Enabled by Default..

How can i Do this This..

And how can i Hide the Tag-Overview

Nice Greets
Sry for my Bad englisch

**Comment by BenjaminHae** [comment]
Hi,
that's fairly simple. Just edit the file `js/plugins/tags.js` as follows:

1. Remove or comment line 29
2. Add this line after line 30:
```
enableGrouping();
```
Good luck.

**Comment by BenjaminHae** [comment]
As you have not replied further, I consider this resolved. If you have any further questions please reopen this issue or create a new issue.
