### ISSUE TITLE
random_login_stamp

### ISSUE THREAD

**Issue by CoderJason123** [zeruniverse/Password-Manager#243]
Hello.  when i try to log in, check.php throws an exception here
if (!isset($_SESSION['random_login_stamp']) || $_SESSION['random_login_stamp'] == '') {

I know this value is set in info.php.  and on that page, i can see the value --- 
I am on a mac, php 7.1.23.

Any ideas as to what may be going on?  Thank you kindly.

**Comment by zeruniverse** [comment]
Can you post full error.log?

**Comment by CoderJason123** [comment]
I'm not getting much of anything in error log.  However, FWIW, it looks like an issue overall with sessions not working in my instance.  It's not the code, something in my set up.  I've reinstalled apache and gone thru the motions.... no luck so far ....

**Comment by CoderJason123** [comment]
Actually - sorry, what seems to be failing is login --- so on post, you can see my error log i added below which is what i get....
function checksession($link)
{
    global $SERVER_TIMEOUT, $HOSTDOMAIN;
    session_start();
    if (!isset($_SESSION['loginok']) || $_SESSION['loginok'] != 1) {
        error_log('session not set');
        logout();

        return false;
    }

**Comment by zeruniverse** [comment]
Please make sure you have enabled https and have a valid certificate (or an
exception).

**Comment by CoderJason123** [comment]
yeah, it all looks good.  I'm sorry i am having trouble getting a better description of what is going on.  I am using version 10.x.

It's almost like the redirect to window.location.href = "./password.php"; in index.js on the call to backend.js is happening before do login gets to call check.php.

is that possible?  i'm not an expert on javascript promises and chained "then"....

**Comment by zeruniverse** [comment]
So you mean at login page, it jumps to password.php without calling
check.php?

**Comment by CoderJason123** [comment]
Let me try to get a handle on it instead of chasing down the rabbit hole :).

**Comment by CoderJason123** [comment]
I'm gonna close this issue - thank you for the input, this is some configuration issue on my side and not an issue with the code.  Thank you kindly.
