### ISSUE TITLE
Positive comment and thank you

### ISSUE THREAD

**Issue by CoderJason123** [zeruniverse/Password-Manager#244]
You've made a very nice piece of code here.  I can say this after looking at tons of projects related to open source password managers and being a developer for 20 years.

It was fun to play with php again in this way, and the ease of implementation and javascript vanilla approach is fantastic, as opposed to the approach that has thousands of libraries and challenging to use build tools.

As something fun, one of the fields you store might want to include the favicon from a website.  Would look nice in the table. 

I plan to monitor this project and perhaps someday do some pull requests, but right now I want to enjoy what you have created to share.  Thank you.

**Comment by BenjaminHae** [comment]
Thank you!

**Comment by zeruniverse** [comment]
Thank you!

**Comment by BenjaminHae** [comment]
> As something fun, one of the fields you store might want to include the favicon from a website. Would look nice in the table.

Btw. this should be pretty easy. Just take a look at the file [`src/js/plugins/linkButton.js`](https://github.com/zeruniverse/Password-Manager/blob/master/src/js/plugins/linkButton.js).
The nicer way to it would be to not only take the link, but also store the real favicon in the fields (privacy reasons) - this would be a bit harder.
