### ISSUE TITLE
Import problem with Username filed

### ISSUE THREAD

**Issue by fabiomarchesi77** [zeruniverse/Password-Manager#246]
Import from CSV works but not for the field "Username", it is empty.

This is the content of my CSV:
`name,username,password,url,comment,tags

"my account name","servizimultimediali","mypassword","https://mysite/","",""`

**Comment by BenjaminHae** [comment]
The column must be named as the custom field. Beware: This is not the header of the column in the manager itself.
This is the definition of the custom field "user":
`"user":{"colname":"Username","hint":"","cls":" hidden-xs","position":1,"count":4}`
The header is "Username", but the field is called "user".
So if you rename the column in your csv to user everything should work.
