### ISSUE TITLE
Complete rework

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#248]
I've started a rework of this project that is based on Symfony, ReactJS and the WebCrypto API (the last part is the most important one).

I've just published a [first version](https://github.com/BenjaminHae/modern-password-manager/releases/tag/v0.0.1-alpha).
The main thing currently missing is **styling**. If there is anybody who would like to participate I'd be very happy :)

If anyone has the time to test it: please give me feedback. The most important stuff right now are bugs and weird behavior.

There is a rudimentary plugin system present for the frontend: `/reactClient/my-app/src/plugin` this allows easy addition of some functionality. This system will be extended to match the one in the "old version" of the password manager.

You can import CSV files of passwords.

**Comment by zeruniverse** [comment]
Close now as this rework will not be merged into this project
