### ISSUE TITLE
Import CSV failed.

### ISSUE THREAD

**Issue by zeruniverse** [zeruniverse/Password-Manager#249]
Hi @BenjaminHae,
I found this piece of code is crashing csv import:
https://github.com/zeruniverse/Password-Manager/blame/master/src/js/main.js#L73
because the separator at export is `,` instead of `;`.

Btw, why `export_raw` dropped file support? https://github.com/zeruniverse/Password-Manager/blob/master/src/js/common/recoveryBackend.js#L152

**Comment by BenjaminHae** [comment]
> I found this piece of code is crashing csv import:
> https://github.com/zeruniverse/Password-Manager/blame/master/src/js/main.js#L73
> because the separator at export is `,` instead of `;`.

Mh, that's weird. It should have guessed the separator from the data. But it's been a long time so I could be wrong.

> Btw, why `export_raw` dropped file support? https://github.com/zeruniverse/Password-Manager/blob/master/src/js/common/recoveryBackend.js#L152

I have no idea ;)

**Comment by BenjaminHae** [comment]
I'm closing it as you've fixed everything. Is that ok?

**Comment by zeruniverse** [comment]
Cool. If you finished the new Password Manager, I can put it at top of README to redirect the traffic.

**Comment by BenjaminHae** [comment]
Thank you! It'll take a little more time. I'll publish it once the browser-plugin works :)
