### ISSUE TITLE
PIN doesn't work on newest version

### ISSUE THREAD

**Issue by GitGoppy** [zeruniverse/Password-Manager#257]
PIN error when trying to login after setting PIN on v. 11.0

**Comment by zeruniverse** [comment]
I personally never had this issue. Could you try if your problem can reproduce on https://phppasswordmanager.sourceforge.io/ ?

**Comment by GitGoppy** [comment]
I can't reproduce it on the demo but the demo doesn't have email verification. Will try to disable email verification and check if it's still broken.

**Comment by zeruniverse** [comment]
My own copy has email verification but I don’t have this issue. It’s not a
result of email verification. Could you try to use privacy mode? This way
you have a clean test environment

**Comment by zeruniverse** [comment]
Is it resolved?
