### ISSUE TITLE
Cannot read property 'importKey' of undefined

### ISSUE THREAD

**Issue by fangzio** [zeruniverse/Password-Manager#258]
Deploy the project locally,can not entry index page in Chrome,but normal in Safari.
![image](https://user-images.githubusercontent.com/18662900/93658694-94537500-fa70-11ea-8109-d0559f891a96.png)
![image](https://user-images.githubusercontent.com/18662900/93658633-f19af680-fa6f-11ea-8ca2-83b5144ba38b.png)

**Comment by BenjaminHae** [comment]
Do you use https? 
The web crypto API used for generating the keys only works on an secure origin.
