### ISSUE TITLE
TypeError: Cannot convert undefined or null to object AFTER LOGIN

### ISSUE THREAD

**Issue by abenati** [zeruniverse/Password-Manager#259]
Hi, trying to login on localhost, I receive this error:
TypeError: Cannot convert undefined or null to object
Don't know how to solve or debug.
Thanks in advance

**Comment by zeruniverse** [comment]
As stated in README, this project only works under HTTPS. If you install in
local host, please make sure you trust your self-signed cert and use
https://localhost/ instead of http://localhost

**Comment by BenjaminHae** [comment]
Why is https necessary on localhost?
It is considered a secure origin by browsers, so the web crypto API should be available?

**Comment by zeruniverse** [comment]
Umm, then I'm not sure what happens exactly. Could you open developer console and paste the error message here?
