### ISSUE TITLE
config.php is being overwritten when updating

### ISSUE THREAD

**Issue by nickbe** [zeruniverse/Password-Manager#26]
I suggest just packing a config_template.php and telling the users to copy/setup a config.php when running for the first time and no config.php is found. This would make updates more easy to handle.

**Comment by zeruniverse** [comment]
I don't see why a template is needed. Config.php is itself a template. And
on the installation/upgrade guide, it's clearly written you should rewrite
config.php

Btw, did you solve the login problem?

**Comment by nickbe** [comment]
Ok. It's no big deal anyway. But you're right if changes are likely to bring incompatible databases anyway.  CLOSED.

**Comment by zeruniverse** [comment]
Fixed by 5fbe322ef65681731fe1a4d2da3d5704f2b7b532.

If config.php not configured, index.php won't open and show hint to set config.php
