### ISSUE TITLE
New Implementation is ready

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#260]
The new implementation is ready. The github repo is [BenjaminHae/modern-password-manager](https://github.com/BenjaminHae/modern-password-manager).

The most important feature is the possibility to use WebAuthN (biometrics) for sign in.
Furthermore, encryption keys are completely handeled by the WebCrypto API in a way that prevents extraction even if someone gets to execute javascript in the context of the application.

**Comment by zeruniverse** [comment]
Added referral to README
