### ISSUE TITLE
Cannot run version 11: error 'sorry-update-your-browser' or am I not meeting the minimum requirements?

### ISSUE THREAD

**Issue by Patron77** [zeruniverse/Password-Manager#263]
Hi there,
On my local development system [no https] I can run version 10 without problems. [the config file has http as the $HOSTDOMAIN]
My system is Debian 10 and Firefox 95.1, 64-bit  [and Google Chrome Version 96.0.4664.93 (Official Build) (64-bit)] and php 7.3 with mysql and Apache 2.4.38. All are up to date.
However, when I try to run version 11, then I get the above error.
Why this is the case?
Is it because I am trying to run it without the secure layer of https? Or, the php has to be ver 7.4 [which is not stated as required]?
Please help/enlighten.
thank you.

**Comment by zeruniverse** [comment]
> Hi there, On my local development system [no https] I can run version 10 without problems. [the config file has http as the $HOSTDOMAIN] My system is Debian 10 and Firefox 95.1, 64-bit [and Google Chrome Version 96.0.4664.93 (Official Build) (64-bit)] and php 7.3 with mysql and Apache 2.4.38. All are up to date. However, when I try to run version 11, then I get the above error. Why this is the case? Is it because I am trying to run it without the secure layer of https? Or, the php has to be ver 7.4 [which is not stated as required]? Please help/enlighten. thank you.

@Patron77 found this unanswered issue. HTTPS is required. Without HTTPS, web crypto is not available.
