### ISSUE TITLE
Current web browser doesn't support the technologies in Android 8.1

### ISSUE THREAD

**Issue by gbrea** [zeruniverse/Password-Manager#267]
I'm trying to log in from a browser on Android and I'm getting this error:
```
We're sorry but your current web browser doesn't support the technologies used by this password manager.
Please upgrade your web browser or enable Local/Session Storage in your browser!

You see this page because your browser doesn't support HTML5 - localStorage and sessionStorage / FileAPI / SubtleCrypto.
If you believe you are using the latest version of a certain browser, please make sure you enabled its HTML5 features. Note for Safari, you should not use the private mode!
If you believe it's a BUG, report here

Here are some recommended web browsers and their download link:
Chrome: download
Firefox: download
Opera: download

Use your new web browser and open this password manager again!
```
But I have recent versions of browsers, and my SO is Android 8.1.0. My device is a Xiaomi Redmi 5 Plus
Chrome → 105.0.5195.68
Firefox → 104.1.0

**Comment by zeruniverse** [comment]
Android 8.1.0 seems to be a very old Android version. Could you try with
other mobile devices? let’s first make sure the server is running well.

**Comment by gbrea** [comment]
In a Xiaomi Redmi Note 9, with Android 11, the behavior is the same.
The server seems to be working correctly because from a firefox on a Laptop with Debian Bullseye it works correctly.
A strange behavior is that, from an incognito tab, it does access correctly. I have this behavior on both devices, both with Android 8 and Android 11.
I have also tried to clear the cache, and the result is the same

**Comment by zeruniverse** [comment]
Would you mind trying the sample website?

https://phppasswordmanager.sourceforge.io

**Comment by gbrea** [comment]
> Would you mind trying the sample website? https://phppasswordmanager.sourceforge.io

On this page it does enter normally. In the apache logs what I get when I try to access is:
```
[02/Sep/2022:21:19:15 +0200] "POST /rest/info.php HTTP/1.1" 200 473 "http://my.domain/" "Mozilla/5.0 (Android 8.1.0; Mobile; rv:104.0) Gecko/104.0 Firefox/104.0" 634
```

**Comment by zeruniverse** [comment]
If sample website works, most likely you didn’t deploy the software
correctly. Please follow installation guide in WIKI.
https://github.com/zeruniverse/Password-Manager/wiki/Installation

Make sure you use https. Http is not supported

**Comment by gbrea** [comment]
Indeed, it was because I was trying to access by http, accessing by https works correctly.
Thank you very much for your time and for helping me realize my mistake.
Congratulations on the job!
