### ISSUE TITLE
Search box suggestion

### ISSUE THREAD

**Issue by nickbe** [zeruniverse/Password-Manager#27]
Maybe it would be better to just leave it always visible (left of the menu button with the mobile view).

**Comment by zeruniverse** [comment]
I'll remove navbar

**Comment by zeruniverse** [comment]
Fixed in a76bdff923021511b63b363b399ebd701ee05ca4

**Comment by nickbe** [comment]
Oops. I didn't mean that you remove the complete bar. Because that one was pretty nice.
I only meant the search field.
The old menu bar was really fine :)

**Comment by zeruniverse** [comment]
Hi, I think other buttons like logout are important. It's better to put
them where you can see directly. Where do you think is bad for current
design?

**Comment by nickbe** [comment]
Having a top menu like before is basically good. Also switching to the top right menu-icon like before. Only the search box should stay permanently either also in the top bar or somewhere below.

Having only pure icons for all sort of stuff is not very elegant. And the design with the black bar on top looks very good. Please go back to this. It's really better!

**Comment by zeruniverse** [comment]
If you prefer navbar, you can add it back according to v9.07. It's easy.
Since this is not a big issue, I would leave it there and maybe add a
navbar back in next version.

Btw, could you login with PIN now?

**Comment by nickbe** [comment]
Thanks. Then I wait until you add the navbar back :)

No luck with the login. I did a fresh install and just reused the database.
I login - I created one item - created pin - logout - then I'm shown the standard login window instead of the proper pincode login.
And the standard login won't work.

**Comment by zeruniverse** [comment]
This is really weird. Could you try
http://phppasswordmanager.sourceforge.net/password.php

This is the newest version and the version I've tested. I totally have no
problem there.

Looking forward to your reply

**Comment by nickbe** [comment]
Yep. It works as expected there !
Is there a problem with the URL localhost/passwords/ or just localhost which i also tried.?

**Comment by zeruniverse** [comment]
There shouldn't be. Local host is equivalent to some domain as well. You
might check your database and see if your pin is written to the pin table.

If the demo works fine to you, it means you do have some problems in your
configuration, at which I can't help. You might need to debug yourself. My
demo is exactly v9.08 just adding database connection info into config.php.
There's no other change.

Please post your solution if you fix it since other people might encounter
into the same problem.

**Comment by nickbe** [comment]
There are some pins stored in the table 'pin' - one of them only minutes old.

But since I have no idea what's going on behind the scenes I don't know what I could search for or how to debug.

**Comment by nickbe** [comment]
btw. deviceid in the pin table and the cookie are the same

**Comment by nickbe** [comment]
Could you bring the old menu header back online?

**Comment by zeruniverse** [comment]
The demo shows the latest release, which does not have the header. So I'm afraid I can't put it back online for now

**Comment by nickbe** [comment]
Just saw the new release :)

I hope you forgive me if I'm annoying you o_O. 

Thanks for everything you did here so far.
Great project - Really. 

Cheers

**Comment by zeruniverse** [comment]
You can download the new v9.08-a with nav bar from sourceforge now.

Thanks for your support as well.
