### ISSUE TITLE
password.js

### ISSUE THREAD

**Issue by nickbe** [zeruniverse/Password-Manager#28]
Looing at the password.js the 
getpwd function is shown hsers like this:

function getpwd(charlist,plength) {
ã€€ã€€var maxPos = charlist.length;
ã€€ã€€var pwd = '';
    var i;
ã€€ã€€for (i = 0; i < parseInt(plength); i++) {
ã€€ã€€ã€€ã€€pwd += charlist.charAt(Math.floor(Math.random() \* maxPos));
ã€€ã€€}
ã€€ã€€return pwd;
}

strange....

**Comment by zeruniverse** [comment]
I'll check that.

**Comment by zeruniverse** [comment]
Fixed by 5fbe322ef65681731fe1a4d2da3d5704f2b7b532
