### ISSUE TITLE
Move export to csv to recover.php

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#29]
How about moving the export to csv function to recover.php to discourage users from having plain-text backups?

If you want to keep the csv export in the main interface I'd suggest merging it into the backup dialog. Semantically that's the place it should be.

**Comment by zeruniverse** [comment]
No. Export csv shouldn't be treated as backup. It's just for export and
should never be kept in dangerous places. I would add a dialogue for export
saying about this

**Comment by zeruniverse** [comment]
Fixed by 5fbe322ef65681731fe1a4d2da3d5704f2b7b532
