### ISSUE TITLE
Untrust function should only be available when pin is active

### ISSUE THREAD

**Issue by nickbe** [zeruniverse/Password-Manager#30]
I think this function should be hidden if the device is not trusted.

**Comment by zeruniverse** [comment]
No. This function clear your username. Or your username will remain in
cookies

**Comment by nickbe** [comment]
Ah I see. But if I don't use the pin, why do you need the cookie then?
Wouldn't it be better to just do that on logout automatically without pin.

**Comment by zeruniverse** [comment]
Untrust simply flush everything out including device name. If you are not strongly against this button, I think I'll keep it.

**Comment by nickbe** [comment]
I didn't know the exact purpose. So of course I'm ok with that.
