### ISSUE TITLE
Pin footer to the bottom

### ISSUE THREAD

**Issue by nickbe** [zeruniverse/Password-Manager#31]
Just a tiny visual tweak:

```
function echofooter()
{
echo '<footer class="footer navbar-fixed-bottom">
```

**Comment by zeruniverse** [comment]
I think if the password list is long, footer shouldn't be fixed as it takes space.

**Comment by nickbe** [comment]
didn't think of that. I'm often more concerned about visual things :)
Smaller footer?

**Comment by zeruniverse** [comment]
I'll just leave it like this. If the list is long, footer is simply invisible.

**Comment by nickbe** [comment]
okay. closed
