### ISSUE TITLE
Optional administrative mode

### ISSUE THREAD

**Issue by nickbe** [zeruniverse/Password-Manager#32]
What do you think about being able to switch (in the config.php) to an administrative mode.
Then jumpto into the signup process right away if no user is present and give him some sort of admin flag.

Then you could provide some ability to delete or lock users.
Also I think the administrator should be able to forbid the self sign-up and just create accounts manually.

**Comment by zeruniverse** [comment]
What can admin do then… he can see nothing from database. If you want to
delete user, do SQL query. However, I don't see why you want to delete user…

**Comment by zeruniverse** [comment]
WON'T IMPLEMENT THIS
