### ISSUE TITLE
Information panel

### ISSUE THREAD

**Issue by nickbe** [zeruniverse/Password-Manager#33]
I played around with the info view - I think it's better readable this way.
Hope you like it:

I changed the field type from textbox to 'label' for this:

```

function showdetail(index){
    var i=parseInt(index);
    var x,s;
    s='<b>'+accountarray[i]["name"]+'</b><br><br>\n';
    s=s+'<table style="width: 100%" font color="#ff0000">';
    s=s+'<col width="90"><col width="auto">';
    for (x in accountarray[i]["other"]) s=s+'<tr><td><font color="#afafaf"><style="font-weight: normal;">'+x+'</td><td><font color="#6d6d6d"><b>'+accountarray[i]["other"][x]+'<b></td></tr>';
    s=s+'</table>';
    $('#details').html(s);
    $("#showdetails").modal("show");
}
```

**Comment by zeruniverse** [comment]
I tried this but don't see much improvement. So you might just use it in your own version :)

**Comment by nickbe** [comment]
Well... displaying a table makes it easier to indentify the attributes.

**Comment by zeruniverse** [comment]
Umm... I'll consider it in next version. But for now I'll leave further improvements for this project aside...

**Comment by zeruniverse** [comment]
Hi @nickbe, you can submit an pull request of this change. It seems you change the textarea to div as well in addition to the function. So a pull request can give me a better sense of your change

**Comment by nickbe** [comment]
I'll try to do this tomorrow. Never had a github client here :)

**Comment by zeruniverse** [comment]
Actually you don't need one. You open the project in web and edit it. GitHub will automatically generate a pull request

**Comment by nickbe** [comment]
Thanks. Hopfully it was correct this way :)
