### ISSUE TITLE
System test

### ISSUE THREAD

**Issue by zeruniverse** [zeruniverse/Password-Manager#40]
It seems we've finished pretty much what's planned. It's time to have a long-term stable release and slow down development pace. But we do need to have a system test before such a release

@BenjaminHae could you help with the test? I think you're currently running the HEAD of master branch.

**Comment by BenjaminHae** [comment]
Yes I'm running HEAD atm. I'll try some things in the next days and keep a list of what worked.
If you have suggestions for things to try I'll do those.

**Comment by zeruniverse** [comment]
Do you have any new features planned but not merged in?

I've tested most features. Maybe you can help with seeing if all dialogues and buttons display normally in all types of devices

**Comment by BenjaminHae** [comment]
There are some features on my list but I don't see this list processed in the next month.
- Make notifications less intrusive(by showing them in the page, not as message box)
- A progress bar when changing the main password
- Ordering the table by accountname
- A button to open the url of an account

And if I've got a lot of time on my hands maybe the possibility to share passwords between users.

I'll try to test the dialogues and buttons, but I've only got a mobile phone. I could use the developer tools in chrome.

**Comment by zeruniverse** [comment]
I've given you push privilege to the repo.

**Comment by zeruniverse** [comment]
I've tested on my browser and fixed some small issues. Since you said you only have a mobile phone, I think the result won't be different from that of my phone. So I'll create a new release including the layout fix now.

**Comment by BenjaminHae** [comment]
Thanks.
