### ISSUE TITLE
Tag function not working

### ISSUE THREAD

**Issue by nickbe** [zeruniverse/Password-Manager#53]
I can see the "Show Tags" button but there's no function behind it.

**Comment by BenjaminHae** [comment]
Did you insert any tags when creating an entry?

**Comment by nickbe** [comment]
Sure. But if you click on the tag option later all you get is an empty page.

**Comment by BenjaminHae** [comment]
Mh I can't reproduce it. Would you mind logging in to the [demo](http://phppasswordmanager.sourceforge.net/password.php) using mytest as user with password testtest. Are you seeing any tags there?

What do you see when you view the page not in a mobile but a normal browser?

**Comment by nickbe** [comment]
Interesting!
It works on your demo.
I tried the online demo though, and it didn't work there either.
Am Do., Mai 12, 2016 16:18 schrieb Benjamin Häublein : Mh I can't reproduce it. Would you mind logging in to the demo (http://phppasswordmanager.sourceforge.net/password.php) using mytest as user with password testtest. Are you seeing any tags there?
 What do you see when you view the page not in a mobile but a normal browser?

**Comment by BenjaminHae** [comment]
This is the demo mentioned in the Readme file.

**Comment by nickbe** [comment]
I create a new install and report back

**Comment by zeruniverse** [comment]
there's no update in 13 days. so I assume it's solved. If not, please reopen it
