### ISSUE TITLE
Edit and view buttons on mobiles are too small

### ISSUE THREAD

**Issue by nickbe** [zeruniverse/Password-Manager#54]
... and to close together

**Comment by zeruniverse** [comment]
I don't think it's small. BTW, seems we didn't change the size recently

**Comment by BenjaminHae** [comment]
I'll take a look at it, but it might take a while as I'm on holidays the next week.

**Comment by nickbe** [comment]
Have a good time then :)

**Comment by zeruniverse** [comment]
@nickbe I made a new commit to master branch. this gives you more space between these two icons. hopefully you won't mistouch anymore in mobile phone.

please give me your feedback.

**Comment by nickbe** [comment]
I'll report back after the weekend :)

**Comment by nickbe** [comment]
Work fine here.
Thanks!!!
Am Mi., Mai 25, 2016 23:05 schrieb Jeffery Zhao : @nickbe (https://github.com/nickbe) I made a new commit to master branch. this gives you more space between these two icons. hopefully you won't mistouch anymore in mobile phone.
 please give me your feedback.

**Comment by nickbe** [comment]
Ithink you can close this.
Thanks!!!
