### ISSUE TITLE
option to disable the javascript messages

### ISSUE THREAD

**Issue by nickbe** [zeruniverse/Password-Manager#55]
Is there an option to disable all the **saved** and **updated** javascript message boxes?
I have to go through 400 account records now and I'd find it much nicer to have a simple
bootstrap message banner below the menu for this kind of messages.

**Comment by BenjaminHae** [comment]
I looked into it a while ago, the problem is, that after the alert the whole page is reloaded, so it's not that easy to implement.
It would be better practice to just reload the table and tags after editing/adding/deleting an account - then showing a notification instead of an alert would be trivial.

**Comment by zeruniverse** [comment]
We can use Ajax. That is, put all dynamic contents in a seperate php file.
But yes, it's not a trivial work.

**Comment by nickbe** [comment]
Well For me the messages are not needed anyway. Can't you just disable them?

**Comment by zeruniverse** [comment]
Temp solution for you: open password.php using notepad, search for 'alert'
and delete all of them.

**Comment by nickbe** [comment]
Yeah I already did this for now. 
Just thought this is a general improvement that I should report.

**Comment by BenjaminHae** [comment]
I'll give it a try.

**Comment by nickbe** [comment]
Thanks Benjamin :+1:

**Comment by BenjaminHae** [comment]
@nickbe I think I've got it, but as this is a major change I'd be glad if you tested it before I'll merge it to the master branch. You just need the files `src/password_ajax.php` and `src/password.php` from [my development branch](https://github.com/BenjaminHae/Password-Manager/tree/ajax)

**Comment by nickbe** [comment]
I'll test this later today and report the results to you.

**Comment by nickbe** [comment]
There seems to be a problem with refreshing the view after deleteing an entry.
Entry is still visible and can be even openend, but after F5 it's gone.

Otherwise the messages look really fine this way.

**Comment by BenjaminHae** [comment]
@nickbe thanks. It should work now. I just pulled everything to master.

**Comment by nickbe** [comment]
Will update the live system tonight. 
Thanks!!!
