### ISSUE TITLE
Decrypting the passwords and loading time

### ISSUE THREAD

**Issue by nickbe** [zeruniverse/Password-Manager#58]
It seems that the login takes considerable more time after we entered 150 accounts.
Is this because the passwords are decrypted when loading?

If so, then I suggest decryption should happen when I need to view a certain password and press the button.

**Comment by zeruniverse** [comment]
No. It's decrypting the account name. Note tags and accounts are both encrypted.

**Comment by BenjaminHae** [comment]
After I'm done converting everything to ajax we could implement pagination to speed things up.

**Comment by zeruniverse** [comment]
Great idea. But how would you do global search then?

**Comment by BenjaminHae** [comment]
We could show the first 25 accounts and then decrypt the rest in the background.

**Comment by nickbe** [comment]
Mmh. Not good. I'm scrolling through 275 account entries here. And I'd rather wait some more when loading. So he's absolutely right. Searching quickly is more important than loading time.

Even the browser internal search function is essential here. 

Maybe it's best just to leave everything as it is.

**Comment by zeruniverse** [comment]
First I would like to know how long it takes. Then if it's extremely bad, I
suggest we do a cache in localstorage (this is not simple at first look)
