### ISSUE TITLE
Prevent loosing valuable passwords

### ISSUE THREAD

**Issue by nickbe** [zeruniverse/Password-Manager#60]
I really suggest that the password generation button is only visible if the password field is empty.
It's too easy to accidentially press the button.

**Comment by zeruniverse** [comment]
This is why alert should not be disabled.

**Comment by zeruniverse** [comment]
I'll working to implement an optional logging system. All deletion/refreshing will be logged.

**Comment by nickbe** [comment]
Well, then I know I made a mistake :)
But how can I revert what I've done?

**Comment by zeruniverse** [comment]
As I said, I'll implement logging feature. So you can find your old password from log

**Comment by nickbe** [comment]
Ah ok. So but then you'd also have to encrypt the log, right?

**Comment by zeruniverse** [comment]
LOG can't be encrypted. Or if you change password, it will have problem.
But why I can't log old password without encryption?

**Comment by nickbe** [comment]
That's simple. Because as an administrator I can tell that most users change passwords to be similar to the old one. So I wouldn't want anyone to see old passwords.

But why don't you just show a warning message before changing an existing password and make sure the user did want to change the existing one?

**Comment by zeruniverse** [comment]
This is what the software like currently right?

**Comment by nickbe** [comment]
When I change the password right now, there's no warning message whatsoever. That's why I asked for a warning in the first place. So you say there should be a message?

**Comment by zeruniverse** [comment]
I remember there was one. Unless @BenjaminHae deleted the alert…

**Comment by BenjaminHae** [comment]
Mh, could be that I deleted it as you could always dismiss the changes. I've got a nice idea that won't disturb users who now what they are doing and helps inexperienced users.

The idea is to show a [popover](http://www.w3schools.com/bootstrap/bootstrap_popover.asp) under the eye button when the user clicks the refresh password button. The popover reads "click here to get your old password back".

**Comment by nickbe** [comment]
What about this:
If there's a password set, then just ask the user to **manually** delete the password field before generating a new one.

This will prevent a simple override. It's easy to delete the field content by hand and you have to willingly do it. And when it's empty you just press **generate**

**Comment by BenjaminHae** [comment]
I think a new user will learn after he presses the regenerate button the first time.
For a "poweruser" first deleting everything will add a lot of hassle.

Especially if you're not happy with the autogenerated password. You'd have to delete everything until you'd get a good one.

**Comment by nickbe** [comment]
The thing is: I observed our secretary adding several accounts. Every once in a while she (for whatever reason) pressed the gen button. And then with a "whoops" closed the window. But instead of discarding she saved. I can assure you that this seemeingly stupid behaviour is absolutely standard. I know because I'm in this business for 25 years now. Users do everything wrong that is possible and you have to prevent them from doing wrong in the first place.

**Comment by zeruniverse** [comment]
I believe #62 fixed this. So I'll close this issue.

**Comment by nickbe** [comment]
Then I'd definetely prefer to disable logging!!!

**Comment by zeruniverse** [comment]
Alright.

**Comment by nickbe** [comment]
Is there an option for this? (Disabling log)

**Comment by zeruniverse** [comment]
Currently there's no log feature
