### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by zeruniverse** [zeruniverse/Password-Manager#64]
Hi @BenjaminHae 

I took a look at your new commits and it seems you try to add pagination support (LN 545 in password.php) but there's no pagination yet. 

From the first look, I think it's not hard to add pagination but it seems the search / cloud filter features will be undermined if we do this. I think cloud filter and search should be global, and therefore my first thought is to make a big table where you put everything and maintain a attribute (let's say `visible-id`) for each `<tr>`. Normally, `visible-id` will be same as `id` (1,2,3...). But when a filter / search is enabled, every entry filtered out will have `visible-id` as `-1` and then you sort other entries by their original `id`, small to big. So you can then show entry with `visible-id` 1 to N if user wants page 1 or N to 2N if user wants page 2...

Please let me know what you think about this implementation.

**Comment by BenjaminHae** [comment]
I have the feeling that `visible-id` would not be necessary, I think it adds some complexity, but I can't put my finger on it.
Maybe we could just use a class `filtered` which is set for every row not fitting a criteria, then use jQuery to select the first `1..N` of every row which isn't of this class and hide everything else?

A second solution would be to just keep an array of id's whose values match and then do the pagination from there on. 

Probably the first solution is faster than the second one and I would hope faster than yours as we could use jQuery magic.

None of these solutions uses `showtable` so a third solution would be to purge the table every time we show something else and do the filtering just by creating subsets of `accountarray` which we then feed to `showtable`.

And now I'm sad I don't have time ;)

**Comment by BenjaminHae** [comment]
Another solution is [DataTables](https://datatables.net/) which claims to do exactly what we want with zero configuration.

**Comment by zeruniverse** [comment]
I can look into it when I have time

**Comment by zeruniverse** [comment]
@BenjaminHae I made some changes on functions you implemented. Please let me know if anything goes wrong.

**Comment by BenjaminHae** [comment]
@zeruniverse If it's alright with you I'm going to reimplement the tag functions as I'm using them a lot and searching isn't the same.

**Comment by zeruniverse** [comment]
Sure. Actually it's easy. You just need to add all tag code back. And after
clicking tag filter or resetting, you refresh the datatable. To me it seems
datatable counts invisible entries (haven't verified yet), if it's the
case, maybe more work is needed.
