### ISSUE TITLE
Question: Is there a reason we destroy and recreate DataTable on Resize?

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#79]
In `document.ready` we set it up so that on every resize the DataTable gets reinitiated:

```
$( window ).resize(function() {
  if(datatablestatus!=null){
      datatablestatus.destroy();
      datatablestatus=$("#pwdlist").DataTable({ordering:false, info:true, "lengthMenu": [ [10, 25, 50, 100, 200, -1], [10, 25, 50, 100, 200, "All"] ] });
  }
});
```

Is this necessary? I just deleted it on my test installation and everything worked fine when resizing, even hiding the tags when there isn't enough space works.
If there is a reason maybe `datatablestatus.draw()` is enough?

**Comment by zeruniverse** [comment]
If you resize a Chrome window from laptop size to mobile phone size, you will find the datatable isn't responsive. So I add this.

You are right, draw() might be OK.

**Comment by BenjaminHae** [comment]
Hm I can't reproduce it. Weird. As I can't test it let's stay with destroy.

**Comment by zeruniverse** [comment]
Well, did you first comment out the destroy()? You should be able to reproduce it if you delete the entire function.

**Comment by zeruniverse** [comment]
@BenjaminHae Could I know your email address? I want some help from you. You can [send me an email](mailto: zzy8200@gmail.com)  if you don't want to publish your email address.

**Comment by BenjaminHae** [comment]
I deleted the whole resize function.

**Comment by zeruniverse** [comment]
Ok. I can take care of this
