### ISSUE TITLE
Password Change Date

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#84]
When I found out about the dropbox leak I wanted to know when I last changed this password, but there's no way to find that out.
So I propose a date field that automatically get's updated when changing the password(but can be set manually). This should all be easy, but I'm short on time right now. @zeruniverse if you have time and muse go ahead. Otherwise would you keep this as an reminder for me?

**Comment by zeruniverse** [comment]
You can build an 'other' field recording time stamp. But I don't see why it should be updated manually sometimes. I suggest treat it specially. I.e. Don't use field settings for it, and let it always exist. Don't show it in edit or create modal. Only show it in details modal. And only update it when the password field changes

**Comment by zeruniverse** [comment]
Last change date will show in details
