### ISSUE TITLE
Fields never used was not removed completely.

### ISSUE THREAD

**Issue by zeruniverse** [zeruniverse/Password-Manager#87]
@BenjaminHae Headers are removed. But cells in tbody are not.

**Comment by zeruniverse** [comment]
The reason for this bug is row.add() does not add the rows to HTML. So, 

``` JavaScript
for (x in fields) {
         if (fields[x]["count"] == 0) {
             $("."+x+"cell").remove();
         }
     }
```

does not work

Temporary fix is showing all cells, regardless of whether they are ever used

**Comment by BenjaminHae** [comment]
I have a short term solution in mind(adding css dynamically) but I think it's not better than to just show all fields. The long term solution will take a litter longer - but I already know what to do. I could have time in two weeks.
