### ISSUE TITLE
User level ?

### ISSUE THREAD

**Issue by coelhocarlos** [zeruniverse/Password-Manager#89]
Fantastic app but need a user  level 

one two tree levels

**Comment by zeruniverse** [comment]
Sorry, what do you suppose to do with user level? 

For this app, encryptions are at web browser, the server doesn't know user's data. So even if you have access to the server, you can't get access to another user's data. So I don't know what else `a higher level user` can do other than controlling his own account.

**Comment by nickbe** [comment]
I agree. if you have access to the server itself you're able to delete whole accounts anyway. Otherwise the system is working on a user registration basis. So everyone is on his own anyway.

**Comment by zeruniverse** [comment]
Close due to no response. Please reopen if you are not satisfied with my answer.
