### ISSUE TITLE
PDO::MYSQL_ATTR_MAX_BUFFER_SIZE not supported with mysqlnd

### ISSUE THREAD

**Issue by ChriBer** [zeruniverse/Password-Manager#90]
PDO::MYSQL_ATTR_MAX_BUFFER_SIZE is not supported with mysqlnd. mysqlnd is default as of PHP 5.4.
Password-Manager 9.09 didn't work in my setup. After removing this argument from the sqllink.php, it works again. Maybe it's possible to check if it exists before using it?
By the way, nice job! ;-)

**Comment by zeruniverse** [comment]
Yes, for now I'll put [an alternative `sqllink.php` file](https://github.com/zeruniverse/Password-Manager/releases/download/9.09/sqllink_mysqlnd.php) without this variable on the README file. So people running `mysqlnd` can download this file. But it seems `mysqld` and `mariadb` need this variable.

**Comment by zeruniverse** [comment]
@ChriBer I wrote a new `sqllink.php` which should check the existence of this variable. Could you try this and tell me whether this one works? Download link: https://raw.githubusercontent.com/zeruniverse/Password-Manager/master/src/function/sqllink.php

**Comment by ChriBer** [comment]
Doesn't work.
PHP Fatal error:  Uncaught Error: Undefined class constant 'MYSQL_ATTR_MAX_BUFFER_SIZE' in /var/www/pass/function/sqllink.php:12

**Comment by zeruniverse** [comment]
@ChriBer OK. But anyway I think the alternative sqllink.php temporary solves the problem.

It's pretty weird 'cause I wrote a try clause. It should go to 'catch' part if something goes wrong. Thanks for your feedback. Sadly I don't have the mysqlnd environment for now. It's great if you can debug a little bit and submit a pull request. Otherwise just use the mysqlnd version of sqllink.php.

Cc @BenjaminHae for this issue.

**Comment by ChriBer** [comment]
This file (renamed to txt because of upload restrictions) works for me:
[sqllink.txt](https://github.com/zeruniverse/Password-Manager/files/458348/sqllink.txt)

**Comment by zeruniverse** [comment]
Could you submit a pull request? So you'll be included in the contribution
list on GitHub page

**Comment by ChriBer** [comment]
Hope I did it right... I'm not really familiar with github...
