### ISSUE TITLE
Upgrade -> Login Error

### ISSUE THREAD

**Issue by BenjaminHae** [zeruniverse/Password-Manager#92]
Did something change in the login progress for the release?
Do I have to reload every user manually or could I just alter the database and it works?

I tried it the easy way(changing the database) and logging in doesn't work anymore: check.php always returns 1.
Logging in using an existing PIN works though.

**Comment by zeruniverse** [comment]
Yes, reduced_info() is changed

**Comment by BenjaminHae** [comment]
Where do I find it? Searching the repository doesn't find it.

**Comment by BenjaminHae** [comment]
ah nevermind. It's in `password.js`

**Comment by BenjaminHae** [comment]
We need a way to upgrade this app. If there's more than one (physical) user it's not feasible to do it through backup and restore.
Maybe we offer a way to login to the old version and then migrate it on the client(as nothing can be decrypted on the server) to the new version when the user logs in. That way we would need two databases but it's still better than forcing everyone to do a backup and restore.

Maybe there are simpler solutions but in my opinion something like this is is a must if we want to get others to use this manager.

**Comment by zeruniverse** [comment]
Umm, you should know the user might come from different old versions. It takes too much time if we need to support every old version. And btw, I think the newest version is pretty stable and I won't touch the encryption in a pretty long period of time.

**Comment by nickbe** [comment]
I just wanted to test the latest release. We're on Version 9.08 here.
Do I have to expect any problems?

**Comment by zeruniverse** [comment]
Should be no problem if you follow installation instruction.
