### ISSUE TITLE
Admin / User Level

### ISSUE THREAD

**Issue by stevetoza** [zeruniverse/Password-Manager#96]
Hello, 

Thanks for the excellent work. This is linked to #89

Would it be possible for a user management to be created. Where you have an admin user with full access, with the ability to,  add users with just a read only user level and another user level with read / write so "Team Leaders can edit passwords (write/read)" Employees (just read permissions)

Any questions let me know

**Comment by zeruniverse** [comment]
This is not possible unless they use the same password. Passwords created
by A will be encrypted using A's login password before uploading to server.
Then B has no way to decrypt it unless he knows A's password.

**Comment by zeruniverse** [comment]
By 'unless they use the same password', I mean unless they use the same
login password, in which case user level is useless. The logic is: in order
to decrypt a password, you must know the login password of the person
creating this password

**Comment by zeruniverse** [comment]
Closed due to no response
