### ISSUE TITLE
Impossible to establish connection

### ISSUE THREAD

**Issue by Pofilo** [zeruniverse/Password-Manager#97]
Hey !

I just install Password-Manager on my server and wanted to try it out !
So I Sign up and create a test account. I can see in my Mysql database that the user is correctly created.
So after that, I tried to Sign in with this account and I got an error like this:
`?reason=AUTHENTICATION%20ERROR%2C%20PLEASE%20RELOGIN`

But the problem is that I can't find any logs talking about that so I don't know what I'm doing wrong !

The only thing I know is that the password is correctly recognized (if I use a wrong password, it tells it to me). 
And also, just before I get this error, there is a short message saying: (I succeed to to see this by recording what happens on my computer)

> PLEASE WAIT WHILE WE ARE DECRYPTING YOUR PASSWORD...

Do you guys have an idea why I have this problem ?
Thanks :)

**Comment by Pofilo** [comment]
I see on an old issue that it was developped with PHP 5.2 but my server uses 7.0.
Does the problem come from that ?

**Comment by zeruniverse** [comment]
Please edit all mandatory fields in config.php. I guess you didn't edit
your site URL. This field is used for referrer check. If you didn't edit
this field, error like this will occur.

**Comment by zeruniverse** [comment]
Also note the this URL should start with https:// or http://. For example,
for the demo site _pas.jeffery.cc_, I'll set it as _http://pas.jeffery.cc/_

**Comment by Pofilo** [comment]
Thanks for your answer. I don't think I made a mistake, but here are the fields I configured:
- `DB_HOST` with the good IP
- `DB_NAME` with the name of the database well configured with _initial.sql_
- `DB_USER` and `DB_PASSWORD` correctly
- the database seems to be well configured as if a wrong password is entered, it is recognized (moreover, there is entries in the database which seems to be correct).
- `HOSTDOMAIN` with _https://example.com/_ 
- I also changed the default timezone with _Europe/Paris_

Otherwise, all the files and other parameters were unchanged. I didn't give other rights on the file and I'm using Apache and PHP 7.0.

EDIT: delete of referal of my instance of Password-Manager

**Comment by zeruniverse** [comment]
Sorry for this issue.

I just checked your website and confirmed that the problem is caused by referrer (If I block my browser to send referrer, things work well). If your `HOSTDOMAIN` is exactly `https://pm.pofilo.fr/`, this is very weird. I'll do some more tests.

**Comment by Pofilo** [comment]
Okay, this was really strange. I try (again) to reinstall it and it seems to work now !

I will check and think if I did something differently the last time but I don't remember right now ..

Thanks for the support and for this project man !

**Comment by zeruniverse** [comment]
I think you misspelled your HOSTDOMAIN last time. You are welcome to use my project and ask questions :)
